// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: product_info/v1/product_info.proto

package productinfov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProductInfo carries display resources for one product.
// Kind-agnostic — consumers should not branch on source type.
type ProductInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable identifier (e.g. "google", "anthropic", "claude-code").
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Human-readable display name.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Public logo/icon URL.
	IconUrl string `protobuf:"bytes,3,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	// Official website URL.
	WebsiteUrl    string `protobuf:"bytes,4,opt,name=website_url,json=websiteUrl,proto3" json:"website_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductInfo) Reset() {
	*x = ProductInfo{}
	mi := &file_product_info_v1_product_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductInfo) ProtoMessage() {}

func (x *ProductInfo) ProtoReflect() protoreflect.Message {
	mi := &file_product_info_v1_product_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductInfo.ProtoReflect.Descriptor instead.
func (*ProductInfo) Descriptor() ([]byte, []int) {
	return file_product_info_v1_product_info_proto_rawDescGZIP(), []int{0}
}

func (x *ProductInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ProductInfo) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *ProductInfo) GetWebsiteUrl() string {
	if x != nil {
		return x.WebsiteUrl
	}
	return ""
}

var File_product_info_v1_product_info_proto protoreflect.FileDescriptor

const file_product_info_v1_product_info_proto_rawDesc = "" +
	"\n" +
	"\"product_info/v1/product_info.proto\x12\x0fproduct_info.v1\"|\n" +
	"\vProductInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x19\n" +
	"\bicon_url\x18\x03 \x01(\tR\aiconUrl\x12\x1f\n" +
	"\vwebsite_url\x18\x04 \x01(\tR\n" +
	"websiteUrlB>Z<code-code.internal/go-contract/product_info/v1;productinfov1b\x06proto3"

var (
	file_product_info_v1_product_info_proto_rawDescOnce sync.Once
	file_product_info_v1_product_info_proto_rawDescData []byte
)

func file_product_info_v1_product_info_proto_rawDescGZIP() []byte {
	file_product_info_v1_product_info_proto_rawDescOnce.Do(func() {
		file_product_info_v1_product_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_info_v1_product_info_proto_rawDesc), len(file_product_info_v1_product_info_proto_rawDesc)))
	})
	return file_product_info_v1_product_info_proto_rawDescData
}

var file_product_info_v1_product_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_product_info_v1_product_info_proto_goTypes = []any{
	(*ProductInfo)(nil), // 0: product_info.v1.ProductInfo
}
var file_product_info_v1_product_info_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_product_info_v1_product_info_proto_init() }
func file_product_info_v1_product_info_proto_init() {
	if File_product_info_v1_product_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_info_v1_product_info_proto_rawDesc), len(file_product_info_v1_product_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_product_info_v1_product_info_proto_goTypes,
		DependencyIndexes: file_product_info_v1_product_info_proto_depIdxs,
		MessageInfos:      file_product_info_v1_product_info_proto_msgTypes,
	}.Build()
	File_product_info_v1_product_info_proto = out.File
	file_product_info_v1_product_info_proto_goTypes = nil
	file_product_info_v1_product_info_proto_depIdxs = nil
}
