// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: platform/orchestration/v1/provider_orchestration_service.proto

package orchestrationv1

import (
	v1 "code-code.internal/go-contract/platform/management/v1"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProviderOrchestrationService_ConnectProvider_FullMethodName                           = "/platform.orchestration.v1.ProviderOrchestrationService/ConnectProvider"
	ProviderOrchestrationService_GetProviderConnectSession_FullMethodName                 = "/platform.orchestration.v1.ProviderOrchestrationService/GetProviderConnectSession"
	ProviderOrchestrationService_UpdateProviderAuthentication_FullMethodName              = "/platform.orchestration.v1.ProviderOrchestrationService/UpdateProviderAuthentication"
	ProviderOrchestrationService_UpdateProviderObservabilityAuthentication_FullMethodName = "/platform.orchestration.v1.ProviderOrchestrationService/UpdateProviderObservabilityAuthentication"
)

// ProviderOrchestrationServiceClient is the client API for ProviderOrchestrationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProviderOrchestrationService owns cross-domain provider onboarding and
// credential update flows. Secret material is accepted only at this API
// boundary and is never passed into Temporal workflow payloads.
type ProviderOrchestrationServiceClient interface {
	ConnectProvider(ctx context.Context, in *v1.ConnectProviderRequest, opts ...grpc.CallOption) (*v1.ConnectProviderResponse, error)
	GetProviderConnectSession(ctx context.Context, in *v1.GetProviderConnectSessionRequest, opts ...grpc.CallOption) (*v1.GetProviderConnectSessionResponse, error)
	UpdateProviderAuthentication(ctx context.Context, in *v1.UpdateProviderAuthenticationRequest, opts ...grpc.CallOption) (*v1.UpdateProviderAuthenticationResponse, error)
	UpdateProviderObservabilityAuthentication(ctx context.Context, in *v1.UpdateProviderObservabilityAuthenticationRequest, opts ...grpc.CallOption) (*v1.UpdateProviderObservabilityAuthenticationResponse, error)
}

type providerOrchestrationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProviderOrchestrationServiceClient(cc grpc.ClientConnInterface) ProviderOrchestrationServiceClient {
	return &providerOrchestrationServiceClient{cc}
}

func (c *providerOrchestrationServiceClient) ConnectProvider(ctx context.Context, in *v1.ConnectProviderRequest, opts ...grpc.CallOption) (*v1.ConnectProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.ConnectProviderResponse)
	err := c.cc.Invoke(ctx, ProviderOrchestrationService_ConnectProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerOrchestrationServiceClient) GetProviderConnectSession(ctx context.Context, in *v1.GetProviderConnectSessionRequest, opts ...grpc.CallOption) (*v1.GetProviderConnectSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.GetProviderConnectSessionResponse)
	err := c.cc.Invoke(ctx, ProviderOrchestrationService_GetProviderConnectSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerOrchestrationServiceClient) UpdateProviderAuthentication(ctx context.Context, in *v1.UpdateProviderAuthenticationRequest, opts ...grpc.CallOption) (*v1.UpdateProviderAuthenticationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.UpdateProviderAuthenticationResponse)
	err := c.cc.Invoke(ctx, ProviderOrchestrationService_UpdateProviderAuthentication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerOrchestrationServiceClient) UpdateProviderObservabilityAuthentication(ctx context.Context, in *v1.UpdateProviderObservabilityAuthenticationRequest, opts ...grpc.CallOption) (*v1.UpdateProviderObservabilityAuthenticationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.UpdateProviderObservabilityAuthenticationResponse)
	err := c.cc.Invoke(ctx, ProviderOrchestrationService_UpdateProviderObservabilityAuthentication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProviderOrchestrationServiceServer is the server API for ProviderOrchestrationService service.
// All implementations must embed UnimplementedProviderOrchestrationServiceServer
// for forward compatibility.
//
// ProviderOrchestrationService owns cross-domain provider onboarding and
// credential update flows. Secret material is accepted only at this API
// boundary and is never passed into Temporal workflow payloads.
type ProviderOrchestrationServiceServer interface {
	ConnectProvider(context.Context, *v1.ConnectProviderRequest) (*v1.ConnectProviderResponse, error)
	GetProviderConnectSession(context.Context, *v1.GetProviderConnectSessionRequest) (*v1.GetProviderConnectSessionResponse, error)
	UpdateProviderAuthentication(context.Context, *v1.UpdateProviderAuthenticationRequest) (*v1.UpdateProviderAuthenticationResponse, error)
	UpdateProviderObservabilityAuthentication(context.Context, *v1.UpdateProviderObservabilityAuthenticationRequest) (*v1.UpdateProviderObservabilityAuthenticationResponse, error)
	mustEmbedUnimplementedProviderOrchestrationServiceServer()
}

// UnimplementedProviderOrchestrationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProviderOrchestrationServiceServer struct{}

func (UnimplementedProviderOrchestrationServiceServer) ConnectProvider(context.Context, *v1.ConnectProviderRequest) (*v1.ConnectProviderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConnectProvider not implemented")
}
func (UnimplementedProviderOrchestrationServiceServer) GetProviderConnectSession(context.Context, *v1.GetProviderConnectSessionRequest) (*v1.GetProviderConnectSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProviderConnectSession not implemented")
}
func (UnimplementedProviderOrchestrationServiceServer) UpdateProviderAuthentication(context.Context, *v1.UpdateProviderAuthenticationRequest) (*v1.UpdateProviderAuthenticationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProviderAuthentication not implemented")
}
func (UnimplementedProviderOrchestrationServiceServer) UpdateProviderObservabilityAuthentication(context.Context, *v1.UpdateProviderObservabilityAuthenticationRequest) (*v1.UpdateProviderObservabilityAuthenticationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProviderObservabilityAuthentication not implemented")
}
func (UnimplementedProviderOrchestrationServiceServer) mustEmbedUnimplementedProviderOrchestrationServiceServer() {
}
func (UnimplementedProviderOrchestrationServiceServer) testEmbeddedByValue() {}

// UnsafeProviderOrchestrationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProviderOrchestrationServiceServer will
// result in compilation errors.
type UnsafeProviderOrchestrationServiceServer interface {
	mustEmbedUnimplementedProviderOrchestrationServiceServer()
}

func RegisterProviderOrchestrationServiceServer(s grpc.ServiceRegistrar, srv ProviderOrchestrationServiceServer) {
	// If the following call pancis, it indicates UnimplementedProviderOrchestrationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProviderOrchestrationService_ServiceDesc, srv)
}

func _ProviderOrchestrationService_ConnectProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ConnectProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderOrchestrationServiceServer).ConnectProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderOrchestrationService_ConnectProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderOrchestrationServiceServer).ConnectProvider(ctx, req.(*v1.ConnectProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderOrchestrationService_GetProviderConnectSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetProviderConnectSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderOrchestrationServiceServer).GetProviderConnectSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderOrchestrationService_GetProviderConnectSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderOrchestrationServiceServer).GetProviderConnectSession(ctx, req.(*v1.GetProviderConnectSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderOrchestrationService_UpdateProviderAuthentication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.UpdateProviderAuthenticationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderOrchestrationServiceServer).UpdateProviderAuthentication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderOrchestrationService_UpdateProviderAuthentication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderOrchestrationServiceServer).UpdateProviderAuthentication(ctx, req.(*v1.UpdateProviderAuthenticationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderOrchestrationService_UpdateProviderObservabilityAuthentication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.UpdateProviderObservabilityAuthenticationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderOrchestrationServiceServer).UpdateProviderObservabilityAuthentication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderOrchestrationService_UpdateProviderObservabilityAuthentication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderOrchestrationServiceServer).UpdateProviderObservabilityAuthentication(ctx, req.(*v1.UpdateProviderObservabilityAuthenticationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProviderOrchestrationService_ServiceDesc is the grpc.ServiceDesc for ProviderOrchestrationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProviderOrchestrationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "platform.orchestration.v1.ProviderOrchestrationService",
	HandlerType: (*ProviderOrchestrationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConnectProvider",
			Handler:    _ProviderOrchestrationService_ConnectProvider_Handler,
		},
		{
			MethodName: "GetProviderConnectSession",
			Handler:    _ProviderOrchestrationService_GetProviderConnectSession_Handler,
		},
		{
			MethodName: "UpdateProviderAuthentication",
			Handler:    _ProviderOrchestrationService_UpdateProviderAuthentication_Handler,
		},
		{
			MethodName: "UpdateProviderObservabilityAuthentication",
			Handler:    _ProviderOrchestrationService_UpdateProviderObservabilityAuthentication_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "platform/orchestration/v1/provider_orchestration_service.proto",
}
