// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: platform/support/v1/support_service.proto

package supportv1connect

import (
	v1 "code-code.internal/go-contract/platform/support/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SupportServiceName is the fully-qualified name of the SupportService service.
	SupportServiceName = "platform.support.v1.SupportService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SupportServiceListVendorsProcedure is the fully-qualified name of the SupportService's
	// ListVendors RPC.
	SupportServiceListVendorsProcedure = "/platform.support.v1.SupportService/ListVendors"
	// SupportServiceGetVendorProcedure is the fully-qualified name of the SupportService's GetVendor
	// RPC.
	SupportServiceGetVendorProcedure = "/platform.support.v1.SupportService/GetVendor"
	// SupportServiceListCLIsProcedure is the fully-qualified name of the SupportService's ListCLIs RPC.
	SupportServiceListCLIsProcedure = "/platform.support.v1.SupportService/ListCLIs"
	// SupportServiceGetCLIProcedure is the fully-qualified name of the SupportService's GetCLI RPC.
	SupportServiceGetCLIProcedure = "/platform.support.v1.SupportService/GetCLI"
	// SupportServiceListProductInfosProcedure is the fully-qualified name of the SupportService's
	// ListProductInfos RPC.
	SupportServiceListProductInfosProcedure = "/platform.support.v1.SupportService/ListProductInfos"
	// SupportServiceResolveProviderCapabilitiesProcedure is the fully-qualified name of the
	// SupportService's ResolveProviderCapabilities RPC.
	SupportServiceResolveProviderCapabilitiesProcedure = "/platform.support.v1.SupportService/ResolveProviderCapabilities"
)

// SupportServiceClient is a client for the platform.support.v1.SupportService service.
type SupportServiceClient interface {
	ListVendors(context.Context, *v1.ListVendorsRequest) (*v1.ListVendorsResponse, error)
	GetVendor(context.Context, *v1.GetVendorRequest) (*v1.GetVendorResponse, error)
	ListCLIs(context.Context, *v1.ListCLIsRequest) (*v1.ListCLIsResponse, error)
	GetCLI(context.Context, *v1.GetCLIRequest) (*v1.GetCLIResponse, error)
	ListProductInfos(context.Context, *v1.ListProductInfosRequest) (*v1.ListProductInfosResponse, error)
	ResolveProviderCapabilities(context.Context, *v1.ResolveProviderCapabilitiesRequest) (*v1.ResolveProviderCapabilitiesResponse, error)
}

// NewSupportServiceClient constructs a client for the platform.support.v1.SupportService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSupportServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SupportServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	supportServiceMethods := v1.File_platform_support_v1_support_service_proto.Services().ByName("SupportService").Methods()
	return &supportServiceClient{
		listVendors: connect.NewClient[v1.ListVendorsRequest, v1.ListVendorsResponse](
			httpClient,
			baseURL+SupportServiceListVendorsProcedure,
			connect.WithSchema(supportServiceMethods.ByName("ListVendors")),
			connect.WithClientOptions(opts...),
		),
		getVendor: connect.NewClient[v1.GetVendorRequest, v1.GetVendorResponse](
			httpClient,
			baseURL+SupportServiceGetVendorProcedure,
			connect.WithSchema(supportServiceMethods.ByName("GetVendor")),
			connect.WithClientOptions(opts...),
		),
		listCLIs: connect.NewClient[v1.ListCLIsRequest, v1.ListCLIsResponse](
			httpClient,
			baseURL+SupportServiceListCLIsProcedure,
			connect.WithSchema(supportServiceMethods.ByName("ListCLIs")),
			connect.WithClientOptions(opts...),
		),
		getCLI: connect.NewClient[v1.GetCLIRequest, v1.GetCLIResponse](
			httpClient,
			baseURL+SupportServiceGetCLIProcedure,
			connect.WithSchema(supportServiceMethods.ByName("GetCLI")),
			connect.WithClientOptions(opts...),
		),
		listProductInfos: connect.NewClient[v1.ListProductInfosRequest, v1.ListProductInfosResponse](
			httpClient,
			baseURL+SupportServiceListProductInfosProcedure,
			connect.WithSchema(supportServiceMethods.ByName("ListProductInfos")),
			connect.WithClientOptions(opts...),
		),
		resolveProviderCapabilities: connect.NewClient[v1.ResolveProviderCapabilitiesRequest, v1.ResolveProviderCapabilitiesResponse](
			httpClient,
			baseURL+SupportServiceResolveProviderCapabilitiesProcedure,
			connect.WithSchema(supportServiceMethods.ByName("ResolveProviderCapabilities")),
			connect.WithClientOptions(opts...),
		),
	}
}

// supportServiceClient implements SupportServiceClient.
type supportServiceClient struct {
	listVendors                 *connect.Client[v1.ListVendorsRequest, v1.ListVendorsResponse]
	getVendor                   *connect.Client[v1.GetVendorRequest, v1.GetVendorResponse]
	listCLIs                    *connect.Client[v1.ListCLIsRequest, v1.ListCLIsResponse]
	getCLI                      *connect.Client[v1.GetCLIRequest, v1.GetCLIResponse]
	listProductInfos            *connect.Client[v1.ListProductInfosRequest, v1.ListProductInfosResponse]
	resolveProviderCapabilities *connect.Client[v1.ResolveProviderCapabilitiesRequest, v1.ResolveProviderCapabilitiesResponse]
}

// ListVendors calls platform.support.v1.SupportService.ListVendors.
func (c *supportServiceClient) ListVendors(ctx context.Context, req *v1.ListVendorsRequest) (*v1.ListVendorsResponse, error) {
	response, err := c.listVendors.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GetVendor calls platform.support.v1.SupportService.GetVendor.
func (c *supportServiceClient) GetVendor(ctx context.Context, req *v1.GetVendorRequest) (*v1.GetVendorResponse, error) {
	response, err := c.getVendor.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListCLIs calls platform.support.v1.SupportService.ListCLIs.
func (c *supportServiceClient) ListCLIs(ctx context.Context, req *v1.ListCLIsRequest) (*v1.ListCLIsResponse, error) {
	response, err := c.listCLIs.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GetCLI calls platform.support.v1.SupportService.GetCLI.
func (c *supportServiceClient) GetCLI(ctx context.Context, req *v1.GetCLIRequest) (*v1.GetCLIResponse, error) {
	response, err := c.getCLI.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListProductInfos calls platform.support.v1.SupportService.ListProductInfos.
func (c *supportServiceClient) ListProductInfos(ctx context.Context, req *v1.ListProductInfosRequest) (*v1.ListProductInfosResponse, error) {
	response, err := c.listProductInfos.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ResolveProviderCapabilities calls platform.support.v1.SupportService.ResolveProviderCapabilities.
func (c *supportServiceClient) ResolveProviderCapabilities(ctx context.Context, req *v1.ResolveProviderCapabilitiesRequest) (*v1.ResolveProviderCapabilitiesResponse, error) {
	response, err := c.resolveProviderCapabilities.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// SupportServiceHandler is an implementation of the platform.support.v1.SupportService service.
type SupportServiceHandler interface {
	ListVendors(context.Context, *v1.ListVendorsRequest) (*v1.ListVendorsResponse, error)
	GetVendor(context.Context, *v1.GetVendorRequest) (*v1.GetVendorResponse, error)
	ListCLIs(context.Context, *v1.ListCLIsRequest) (*v1.ListCLIsResponse, error)
	GetCLI(context.Context, *v1.GetCLIRequest) (*v1.GetCLIResponse, error)
	ListProductInfos(context.Context, *v1.ListProductInfosRequest) (*v1.ListProductInfosResponse, error)
	ResolveProviderCapabilities(context.Context, *v1.ResolveProviderCapabilitiesRequest) (*v1.ResolveProviderCapabilitiesResponse, error)
}

// NewSupportServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSupportServiceHandler(svc SupportServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	supportServiceMethods := v1.File_platform_support_v1_support_service_proto.Services().ByName("SupportService").Methods()
	supportServiceListVendorsHandler := connect.NewUnaryHandlerSimple(
		SupportServiceListVendorsProcedure,
		svc.ListVendors,
		connect.WithSchema(supportServiceMethods.ByName("ListVendors")),
		connect.WithHandlerOptions(opts...),
	)
	supportServiceGetVendorHandler := connect.NewUnaryHandlerSimple(
		SupportServiceGetVendorProcedure,
		svc.GetVendor,
		connect.WithSchema(supportServiceMethods.ByName("GetVendor")),
		connect.WithHandlerOptions(opts...),
	)
	supportServiceListCLIsHandler := connect.NewUnaryHandlerSimple(
		SupportServiceListCLIsProcedure,
		svc.ListCLIs,
		connect.WithSchema(supportServiceMethods.ByName("ListCLIs")),
		connect.WithHandlerOptions(opts...),
	)
	supportServiceGetCLIHandler := connect.NewUnaryHandlerSimple(
		SupportServiceGetCLIProcedure,
		svc.GetCLI,
		connect.WithSchema(supportServiceMethods.ByName("GetCLI")),
		connect.WithHandlerOptions(opts...),
	)
	supportServiceListProductInfosHandler := connect.NewUnaryHandlerSimple(
		SupportServiceListProductInfosProcedure,
		svc.ListProductInfos,
		connect.WithSchema(supportServiceMethods.ByName("ListProductInfos")),
		connect.WithHandlerOptions(opts...),
	)
	supportServiceResolveProviderCapabilitiesHandler := connect.NewUnaryHandlerSimple(
		SupportServiceResolveProviderCapabilitiesProcedure,
		svc.ResolveProviderCapabilities,
		connect.WithSchema(supportServiceMethods.ByName("ResolveProviderCapabilities")),
		connect.WithHandlerOptions(opts...),
	)
	return "/platform.support.v1.SupportService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SupportServiceListVendorsProcedure:
			supportServiceListVendorsHandler.ServeHTTP(w, r)
		case SupportServiceGetVendorProcedure:
			supportServiceGetVendorHandler.ServeHTTP(w, r)
		case SupportServiceListCLIsProcedure:
			supportServiceListCLIsHandler.ServeHTTP(w, r)
		case SupportServiceGetCLIProcedure:
			supportServiceGetCLIHandler.ServeHTTP(w, r)
		case SupportServiceListProductInfosProcedure:
			supportServiceListProductInfosHandler.ServeHTTP(w, r)
		case SupportServiceResolveProviderCapabilitiesProcedure:
			supportServiceResolveProviderCapabilitiesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSupportServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSupportServiceHandler struct{}

func (UnimplementedSupportServiceHandler) ListVendors(context.Context, *v1.ListVendorsRequest) (*v1.ListVendorsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.support.v1.SupportService.ListVendors is not implemented"))
}

func (UnimplementedSupportServiceHandler) GetVendor(context.Context, *v1.GetVendorRequest) (*v1.GetVendorResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.support.v1.SupportService.GetVendor is not implemented"))
}

func (UnimplementedSupportServiceHandler) ListCLIs(context.Context, *v1.ListCLIsRequest) (*v1.ListCLIsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.support.v1.SupportService.ListCLIs is not implemented"))
}

func (UnimplementedSupportServiceHandler) GetCLI(context.Context, *v1.GetCLIRequest) (*v1.GetCLIResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.support.v1.SupportService.GetCLI is not implemented"))
}

func (UnimplementedSupportServiceHandler) ListProductInfos(context.Context, *v1.ListProductInfosRequest) (*v1.ListProductInfosResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.support.v1.SupportService.ListProductInfos is not implemented"))
}

func (UnimplementedSupportServiceHandler) ResolveProviderCapabilities(context.Context, *v1.ResolveProviderCapabilitiesRequest) (*v1.ResolveProviderCapabilitiesResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.support.v1.SupportService.ResolveProviderCapabilities is not implemented"))
}
