// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: platform/provider/v1/provider_service.proto

package providerservicev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProviderService_ListProviderSurfaces_FullMethodName       = "/platform.provider.v1.ProviderService/ListProviderSurfaces"
	ProviderService_ListProviders_FullMethodName              = "/platform.provider.v1.ProviderService/ListProviders"
	ProviderService_CreateProvider_FullMethodName             = "/platform.provider.v1.ProviderService/CreateProvider"
	ProviderService_UpdateProvider_FullMethodName             = "/platform.provider.v1.ProviderService/UpdateProvider"
	ProviderService_DeleteProvider_FullMethodName             = "/platform.provider.v1.ProviderService/DeleteProvider"
	ProviderService_ApplyProviderModelCatalog_FullMethodName  = "/platform.provider.v1.ProviderService/ApplyProviderModelCatalog"
	ProviderService_ApplyProviderProbeStatus_FullMethodName   = "/platform.provider.v1.ProviderService/ApplyProviderProbeStatus"
	ProviderService_ProbeProviderObservability_FullMethodName = "/platform.provider.v1.ProviderService/ProbeProviderObservability"
	ProviderService_ProbeProviderModelCatalog_FullMethodName  = "/platform.provider.v1.ProviderService/ProbeProviderModelCatalog"
	ProviderService_WatchProviderStatusEvents_FullMethodName  = "/platform.provider.v1.ProviderService/WatchProviderStatusEvents"
	ProviderService_ListVendors_FullMethodName                = "/platform.provider.v1.ProviderService/ListVendors"
	ProviderService_ListTemplates_FullMethodName              = "/platform.provider.v1.ProviderService/ListTemplates"
	ProviderService_ApplyTemplate_FullMethodName              = "/platform.provider.v1.ProviderService/ApplyTemplate"
)

// ProviderServiceClient is the client API for ProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProviderServiceClient interface {
	ListProviderSurfaces(ctx context.Context, in *ListProviderSurfacesRequest, opts ...grpc.CallOption) (*ListProviderSurfacesResponse, error)
	ListProviders(ctx context.Context, in *ListProvidersRequest, opts ...grpc.CallOption) (*ListProvidersResponse, error)
	CreateProvider(ctx context.Context, in *CreateProviderRequest, opts ...grpc.CallOption) (*CreateProviderResponse, error)
	UpdateProvider(ctx context.Context, in *UpdateProviderRequest, opts ...grpc.CallOption) (*UpdateProviderResponse, error)
	DeleteProvider(ctx context.Context, in *DeleteProviderRequest, opts ...grpc.CallOption) (*DeleteProviderResponse, error)
	ApplyProviderModelCatalog(ctx context.Context, in *ApplyProviderModelCatalogRequest, opts ...grpc.CallOption) (*ApplyProviderModelCatalogResponse, error)
	ApplyProviderProbeStatus(ctx context.Context, in *ApplyProviderProbeStatusRequest, opts ...grpc.CallOption) (*ApplyProviderProbeStatusResponse, error)
	ProbeProviderObservability(ctx context.Context, in *ProbeProviderObservabilityRequest, opts ...grpc.CallOption) (*ProbeProviderObservabilityResponse, error)
	ProbeProviderModelCatalog(ctx context.Context, in *ProbeProviderModelCatalogRequest, opts ...grpc.CallOption) (*ProbeProviderModelCatalogResponse, error)
	WatchProviderStatusEvents(ctx context.Context, in *WatchProviderStatusEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchProviderStatusEventsResponse], error)
	ListVendors(ctx context.Context, in *ListVendorsRequest, opts ...grpc.CallOption) (*ListVendorsResponse, error)
	ListTemplates(ctx context.Context, in *ListTemplatesRequest, opts ...grpc.CallOption) (*ListTemplatesResponse, error)
	ApplyTemplate(ctx context.Context, in *ApplyTemplateRequest, opts ...grpc.CallOption) (*ApplyTemplateResponse, error)
}

type providerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProviderServiceClient(cc grpc.ClientConnInterface) ProviderServiceClient {
	return &providerServiceClient{cc}
}

func (c *providerServiceClient) ListProviderSurfaces(ctx context.Context, in *ListProviderSurfacesRequest, opts ...grpc.CallOption) (*ListProviderSurfacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProviderSurfacesResponse)
	err := c.cc.Invoke(ctx, ProviderService_ListProviderSurfaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ListProviders(ctx context.Context, in *ListProvidersRequest, opts ...grpc.CallOption) (*ListProvidersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProvidersResponse)
	err := c.cc.Invoke(ctx, ProviderService_ListProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) CreateProvider(ctx context.Context, in *CreateProviderRequest, opts ...grpc.CallOption) (*CreateProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProviderResponse)
	err := c.cc.Invoke(ctx, ProviderService_CreateProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) UpdateProvider(ctx context.Context, in *UpdateProviderRequest, opts ...grpc.CallOption) (*UpdateProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProviderResponse)
	err := c.cc.Invoke(ctx, ProviderService_UpdateProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) DeleteProvider(ctx context.Context, in *DeleteProviderRequest, opts ...grpc.CallOption) (*DeleteProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProviderResponse)
	err := c.cc.Invoke(ctx, ProviderService_DeleteProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ApplyProviderModelCatalog(ctx context.Context, in *ApplyProviderModelCatalogRequest, opts ...grpc.CallOption) (*ApplyProviderModelCatalogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyProviderModelCatalogResponse)
	err := c.cc.Invoke(ctx, ProviderService_ApplyProviderModelCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ApplyProviderProbeStatus(ctx context.Context, in *ApplyProviderProbeStatusRequest, opts ...grpc.CallOption) (*ApplyProviderProbeStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyProviderProbeStatusResponse)
	err := c.cc.Invoke(ctx, ProviderService_ApplyProviderProbeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ProbeProviderObservability(ctx context.Context, in *ProbeProviderObservabilityRequest, opts ...grpc.CallOption) (*ProbeProviderObservabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProbeProviderObservabilityResponse)
	err := c.cc.Invoke(ctx, ProviderService_ProbeProviderObservability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ProbeProviderModelCatalog(ctx context.Context, in *ProbeProviderModelCatalogRequest, opts ...grpc.CallOption) (*ProbeProviderModelCatalogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProbeProviderModelCatalogResponse)
	err := c.cc.Invoke(ctx, ProviderService_ProbeProviderModelCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) WatchProviderStatusEvents(ctx context.Context, in *WatchProviderStatusEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchProviderStatusEventsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProviderService_ServiceDesc.Streams[0], ProviderService_WatchProviderStatusEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchProviderStatusEventsRequest, WatchProviderStatusEventsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProviderService_WatchProviderStatusEventsClient = grpc.ServerStreamingClient[WatchProviderStatusEventsResponse]

func (c *providerServiceClient) ListVendors(ctx context.Context, in *ListVendorsRequest, opts ...grpc.CallOption) (*ListVendorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVendorsResponse)
	err := c.cc.Invoke(ctx, ProviderService_ListVendors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ListTemplates(ctx context.Context, in *ListTemplatesRequest, opts ...grpc.CallOption) (*ListTemplatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTemplatesResponse)
	err := c.cc.Invoke(ctx, ProviderService_ListTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerServiceClient) ApplyTemplate(ctx context.Context, in *ApplyTemplateRequest, opts ...grpc.CallOption) (*ApplyTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyTemplateResponse)
	err := c.cc.Invoke(ctx, ProviderService_ApplyTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProviderServiceServer is the server API for ProviderService service.
// All implementations must embed UnimplementedProviderServiceServer
// for forward compatibility.
type ProviderServiceServer interface {
	ListProviderSurfaces(context.Context, *ListProviderSurfacesRequest) (*ListProviderSurfacesResponse, error)
	ListProviders(context.Context, *ListProvidersRequest) (*ListProvidersResponse, error)
	CreateProvider(context.Context, *CreateProviderRequest) (*CreateProviderResponse, error)
	UpdateProvider(context.Context, *UpdateProviderRequest) (*UpdateProviderResponse, error)
	DeleteProvider(context.Context, *DeleteProviderRequest) (*DeleteProviderResponse, error)
	ApplyProviderModelCatalog(context.Context, *ApplyProviderModelCatalogRequest) (*ApplyProviderModelCatalogResponse, error)
	ApplyProviderProbeStatus(context.Context, *ApplyProviderProbeStatusRequest) (*ApplyProviderProbeStatusResponse, error)
	ProbeProviderObservability(context.Context, *ProbeProviderObservabilityRequest) (*ProbeProviderObservabilityResponse, error)
	ProbeProviderModelCatalog(context.Context, *ProbeProviderModelCatalogRequest) (*ProbeProviderModelCatalogResponse, error)
	WatchProviderStatusEvents(*WatchProviderStatusEventsRequest, grpc.ServerStreamingServer[WatchProviderStatusEventsResponse]) error
	ListVendors(context.Context, *ListVendorsRequest) (*ListVendorsResponse, error)
	ListTemplates(context.Context, *ListTemplatesRequest) (*ListTemplatesResponse, error)
	ApplyTemplate(context.Context, *ApplyTemplateRequest) (*ApplyTemplateResponse, error)
	mustEmbedUnimplementedProviderServiceServer()
}

// UnimplementedProviderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProviderServiceServer struct{}

func (UnimplementedProviderServiceServer) ListProviderSurfaces(context.Context, *ListProviderSurfacesRequest) (*ListProviderSurfacesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProviderSurfaces not implemented")
}
func (UnimplementedProviderServiceServer) ListProviders(context.Context, *ListProvidersRequest) (*ListProvidersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProviders not implemented")
}
func (UnimplementedProviderServiceServer) CreateProvider(context.Context, *CreateProviderRequest) (*CreateProviderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProvider not implemented")
}
func (UnimplementedProviderServiceServer) UpdateProvider(context.Context, *UpdateProviderRequest) (*UpdateProviderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProvider not implemented")
}
func (UnimplementedProviderServiceServer) DeleteProvider(context.Context, *DeleteProviderRequest) (*DeleteProviderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProvider not implemented")
}
func (UnimplementedProviderServiceServer) ApplyProviderModelCatalog(context.Context, *ApplyProviderModelCatalogRequest) (*ApplyProviderModelCatalogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyProviderModelCatalog not implemented")
}
func (UnimplementedProviderServiceServer) ApplyProviderProbeStatus(context.Context, *ApplyProviderProbeStatusRequest) (*ApplyProviderProbeStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyProviderProbeStatus not implemented")
}
func (UnimplementedProviderServiceServer) ProbeProviderObservability(context.Context, *ProbeProviderObservabilityRequest) (*ProbeProviderObservabilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProbeProviderObservability not implemented")
}
func (UnimplementedProviderServiceServer) ProbeProviderModelCatalog(context.Context, *ProbeProviderModelCatalogRequest) (*ProbeProviderModelCatalogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProbeProviderModelCatalog not implemented")
}
func (UnimplementedProviderServiceServer) WatchProviderStatusEvents(*WatchProviderStatusEventsRequest, grpc.ServerStreamingServer[WatchProviderStatusEventsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method WatchProviderStatusEvents not implemented")
}
func (UnimplementedProviderServiceServer) ListVendors(context.Context, *ListVendorsRequest) (*ListVendorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVendors not implemented")
}
func (UnimplementedProviderServiceServer) ListTemplates(context.Context, *ListTemplatesRequest) (*ListTemplatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTemplates not implemented")
}
func (UnimplementedProviderServiceServer) ApplyTemplate(context.Context, *ApplyTemplateRequest) (*ApplyTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyTemplate not implemented")
}
func (UnimplementedProviderServiceServer) mustEmbedUnimplementedProviderServiceServer() {}
func (UnimplementedProviderServiceServer) testEmbeddedByValue()                         {}

// UnsafeProviderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProviderServiceServer will
// result in compilation errors.
type UnsafeProviderServiceServer interface {
	mustEmbedUnimplementedProviderServiceServer()
}

func RegisterProviderServiceServer(s grpc.ServiceRegistrar, srv ProviderServiceServer) {
	// If the following call pancis, it indicates UnimplementedProviderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProviderService_ServiceDesc, srv)
}

func _ProviderService_ListProviderSurfaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProviderSurfacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ListProviderSurfaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_ListProviderSurfaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ListProviderSurfaces(ctx, req.(*ListProviderSurfacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ListProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ListProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_ListProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ListProviders(ctx, req.(*ListProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_CreateProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).CreateProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_CreateProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).CreateProvider(ctx, req.(*CreateProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_UpdateProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).UpdateProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_UpdateProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).UpdateProvider(ctx, req.(*UpdateProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_DeleteProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).DeleteProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_DeleteProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).DeleteProvider(ctx, req.(*DeleteProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ApplyProviderModelCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyProviderModelCatalogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ApplyProviderModelCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_ApplyProviderModelCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ApplyProviderModelCatalog(ctx, req.(*ApplyProviderModelCatalogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ApplyProviderProbeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyProviderProbeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ApplyProviderProbeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_ApplyProviderProbeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ApplyProviderProbeStatus(ctx, req.(*ApplyProviderProbeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ProbeProviderObservability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProbeProviderObservabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ProbeProviderObservability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_ProbeProviderObservability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ProbeProviderObservability(ctx, req.(*ProbeProviderObservabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ProbeProviderModelCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProbeProviderModelCatalogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ProbeProviderModelCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_ProbeProviderModelCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ProbeProviderModelCatalog(ctx, req.(*ProbeProviderModelCatalogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_WatchProviderStatusEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchProviderStatusEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProviderServiceServer).WatchProviderStatusEvents(m, &grpc.GenericServerStream[WatchProviderStatusEventsRequest, WatchProviderStatusEventsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProviderService_WatchProviderStatusEventsServer = grpc.ServerStreamingServer[WatchProviderStatusEventsResponse]

func _ProviderService_ListVendors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVendorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ListVendors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_ListVendors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ListVendors(ctx, req.(*ListVendorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ListTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ListTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_ListTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ListTemplates(ctx, req.(*ListTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderService_ApplyTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServiceServer).ApplyTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderService_ApplyTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServiceServer).ApplyTemplate(ctx, req.(*ApplyTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProviderService_ServiceDesc is the grpc.ServiceDesc for ProviderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "platform.provider.v1.ProviderService",
	HandlerType: (*ProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProviderSurfaces",
			Handler:    _ProviderService_ListProviderSurfaces_Handler,
		},
		{
			MethodName: "ListProviders",
			Handler:    _ProviderService_ListProviders_Handler,
		},
		{
			MethodName: "CreateProvider",
			Handler:    _ProviderService_CreateProvider_Handler,
		},
		{
			MethodName: "UpdateProvider",
			Handler:    _ProviderService_UpdateProvider_Handler,
		},
		{
			MethodName: "DeleteProvider",
			Handler:    _ProviderService_DeleteProvider_Handler,
		},
		{
			MethodName: "ApplyProviderModelCatalog",
			Handler:    _ProviderService_ApplyProviderModelCatalog_Handler,
		},
		{
			MethodName: "ApplyProviderProbeStatus",
			Handler:    _ProviderService_ApplyProviderProbeStatus_Handler,
		},
		{
			MethodName: "ProbeProviderObservability",
			Handler:    _ProviderService_ProbeProviderObservability_Handler,
		},
		{
			MethodName: "ProbeProviderModelCatalog",
			Handler:    _ProviderService_ProbeProviderModelCatalog_Handler,
		},
		{
			MethodName: "ListVendors",
			Handler:    _ProviderService_ListVendors_Handler,
		},
		{
			MethodName: "ListTemplates",
			Handler:    _ProviderService_ListTemplates_Handler,
		},
		{
			MethodName: "ApplyTemplate",
			Handler:    _ProviderService_ApplyTemplate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchProviderStatusEvents",
			Handler:       _ProviderService_WatchProviderStatusEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "platform/provider/v1/provider_service.proto",
}
