// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: platform/provider/v1/provider_shared.proto

package providerservicev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProviderPhase describes the lifecycle phase of a provider
// derived from provider config validation.
type ProviderPhase int32

const (
	ProviderPhase_PROVIDER_PHASE_UNSPECIFIED    ProviderPhase = 0
	ProviderPhase_PROVIDER_PHASE_READY          ProviderPhase = 1
	ProviderPhase_PROVIDER_PHASE_INVALID_CONFIG ProviderPhase = 2
	ProviderPhase_PROVIDER_PHASE_REFRESHING     ProviderPhase = 3
	ProviderPhase_PROVIDER_PHASE_STALE          ProviderPhase = 4
	ProviderPhase_PROVIDER_PHASE_ERROR          ProviderPhase = 5
)

// Enum value maps for ProviderPhase.
var (
	ProviderPhase_name = map[int32]string{
		0: "PROVIDER_PHASE_UNSPECIFIED",
		1: "PROVIDER_PHASE_READY",
		2: "PROVIDER_PHASE_INVALID_CONFIG",
		3: "PROVIDER_PHASE_REFRESHING",
		4: "PROVIDER_PHASE_STALE",
		5: "PROVIDER_PHASE_ERROR",
	}
	ProviderPhase_value = map[string]int32{
		"PROVIDER_PHASE_UNSPECIFIED":    0,
		"PROVIDER_PHASE_READY":          1,
		"PROVIDER_PHASE_INVALID_CONFIG": 2,
		"PROVIDER_PHASE_REFRESHING":     3,
		"PROVIDER_PHASE_STALE":          4,
		"PROVIDER_PHASE_ERROR":          5,
	}
)

func (x ProviderPhase) Enum() *ProviderPhase {
	p := new(ProviderPhase)
	*p = x
	return p
}

func (x ProviderPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProviderPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_provider_v1_provider_shared_proto_enumTypes[0].Descriptor()
}

func (ProviderPhase) Type() protoreflect.EnumType {
	return &file_platform_provider_v1_provider_shared_proto_enumTypes[0]
}

func (x ProviderPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProviderPhase.Descriptor instead.
func (ProviderPhase) EnumDescriptor() ([]byte, []int) {
	return file_platform_provider_v1_provider_shared_proto_rawDescGZIP(), []int{0}
}

// ProviderConnectSessionPhase describes the lifecycle phase of a provider
// connect session used for CLI OAuth flows.
type ProviderConnectSessionPhase int32

const (
	ProviderConnectSessionPhase_PROVIDER_CONNECT_SESSION_PHASE_UNSPECIFIED   ProviderConnectSessionPhase = 0
	ProviderConnectSessionPhase_PROVIDER_CONNECT_SESSION_PHASE_PENDING       ProviderConnectSessionPhase = 1
	ProviderConnectSessionPhase_PROVIDER_CONNECT_SESSION_PHASE_AWAITING_USER ProviderConnectSessionPhase = 2
	ProviderConnectSessionPhase_PROVIDER_CONNECT_SESSION_PHASE_PROCESSING    ProviderConnectSessionPhase = 3
	ProviderConnectSessionPhase_PROVIDER_CONNECT_SESSION_PHASE_SUCCEEDED     ProviderConnectSessionPhase = 4
	ProviderConnectSessionPhase_PROVIDER_CONNECT_SESSION_PHASE_FAILED        ProviderConnectSessionPhase = 5
	ProviderConnectSessionPhase_PROVIDER_CONNECT_SESSION_PHASE_EXPIRED       ProviderConnectSessionPhase = 6
	ProviderConnectSessionPhase_PROVIDER_CONNECT_SESSION_PHASE_CANCELED      ProviderConnectSessionPhase = 7
)

// Enum value maps for ProviderConnectSessionPhase.
var (
	ProviderConnectSessionPhase_name = map[int32]string{
		0: "PROVIDER_CONNECT_SESSION_PHASE_UNSPECIFIED",
		1: "PROVIDER_CONNECT_SESSION_PHASE_PENDING",
		2: "PROVIDER_CONNECT_SESSION_PHASE_AWAITING_USER",
		3: "PROVIDER_CONNECT_SESSION_PHASE_PROCESSING",
		4: "PROVIDER_CONNECT_SESSION_PHASE_SUCCEEDED",
		5: "PROVIDER_CONNECT_SESSION_PHASE_FAILED",
		6: "PROVIDER_CONNECT_SESSION_PHASE_EXPIRED",
		7: "PROVIDER_CONNECT_SESSION_PHASE_CANCELED",
	}
	ProviderConnectSessionPhase_value = map[string]int32{
		"PROVIDER_CONNECT_SESSION_PHASE_UNSPECIFIED":   0,
		"PROVIDER_CONNECT_SESSION_PHASE_PENDING":       1,
		"PROVIDER_CONNECT_SESSION_PHASE_AWAITING_USER": 2,
		"PROVIDER_CONNECT_SESSION_PHASE_PROCESSING":    3,
		"PROVIDER_CONNECT_SESSION_PHASE_SUCCEEDED":     4,
		"PROVIDER_CONNECT_SESSION_PHASE_FAILED":        5,
		"PROVIDER_CONNECT_SESSION_PHASE_EXPIRED":       6,
		"PROVIDER_CONNECT_SESSION_PHASE_CANCELED":      7,
	}
)

func (x ProviderConnectSessionPhase) Enum() *ProviderConnectSessionPhase {
	p := new(ProviderConnectSessionPhase)
	*p = x
	return p
}

func (x ProviderConnectSessionPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProviderConnectSessionPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_provider_v1_provider_shared_proto_enumTypes[1].Descriptor()
}

func (ProviderConnectSessionPhase) Type() protoreflect.EnumType {
	return &file_platform_provider_v1_provider_shared_proto_enumTypes[1]
}

func (x ProviderConnectSessionPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProviderConnectSessionPhase.Descriptor instead.
func (ProviderConnectSessionPhase) EnumDescriptor() ([]byte, []int) {
	return file_platform_provider_v1_provider_shared_proto_rawDescGZIP(), []int{1}
}

// ProviderAddMethod identifies the credential add method for a provider.
type ProviderAddMethod int32

const (
	ProviderAddMethod_PROVIDER_ADD_METHOD_UNSPECIFIED ProviderAddMethod = 0
	ProviderAddMethod_PROVIDER_ADD_METHOD_API_KEY     ProviderAddMethod = 1
	ProviderAddMethod_PROVIDER_ADD_METHOD_CLI_OAUTH   ProviderAddMethod = 2
)

// Enum value maps for ProviderAddMethod.
var (
	ProviderAddMethod_name = map[int32]string{
		0: "PROVIDER_ADD_METHOD_UNSPECIFIED",
		1: "PROVIDER_ADD_METHOD_API_KEY",
		2: "PROVIDER_ADD_METHOD_CLI_OAUTH",
	}
	ProviderAddMethod_value = map[string]int32{
		"PROVIDER_ADD_METHOD_UNSPECIFIED": 0,
		"PROVIDER_ADD_METHOD_API_KEY":     1,
		"PROVIDER_ADD_METHOD_CLI_OAUTH":   2,
	}
)

func (x ProviderAddMethod) Enum() *ProviderAddMethod {
	p := new(ProviderAddMethod)
	*p = x
	return p
}

func (x ProviderAddMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProviderAddMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_provider_v1_provider_shared_proto_enumTypes[2].Descriptor()
}

func (ProviderAddMethod) Type() protoreflect.EnumType {
	return &file_platform_provider_v1_provider_shared_proto_enumTypes[2]
}

func (x ProviderAddMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProviderAddMethod.Descriptor instead.
func (ProviderAddMethod) EnumDescriptor() ([]byte, []int) {
	return file_platform_provider_v1_provider_shared_proto_rawDescGZIP(), []int{2}
}

// ProviderOAuthObservabilityProbeOutcome describes the result of an
// observability probe triggered via CLI OAuth.
type ProviderOAuthObservabilityProbeOutcome int32

const (
	ProviderOAuthObservabilityProbeOutcome_PROVIDER_O_AUTH_OBSERVABILITY_PROBE_OUTCOME_UNSPECIFIED  ProviderOAuthObservabilityProbeOutcome = 0
	ProviderOAuthObservabilityProbeOutcome_PROVIDER_O_AUTH_OBSERVABILITY_PROBE_OUTCOME_EXECUTED     ProviderOAuthObservabilityProbeOutcome = 1
	ProviderOAuthObservabilityProbeOutcome_PROVIDER_O_AUTH_OBSERVABILITY_PROBE_OUTCOME_THROTTLED    ProviderOAuthObservabilityProbeOutcome = 2
	ProviderOAuthObservabilityProbeOutcome_PROVIDER_O_AUTH_OBSERVABILITY_PROBE_OUTCOME_AUTH_BLOCKED ProviderOAuthObservabilityProbeOutcome = 3
	ProviderOAuthObservabilityProbeOutcome_PROVIDER_O_AUTH_OBSERVABILITY_PROBE_OUTCOME_UNSUPPORTED  ProviderOAuthObservabilityProbeOutcome = 4
	ProviderOAuthObservabilityProbeOutcome_PROVIDER_O_AUTH_OBSERVABILITY_PROBE_OUTCOME_FAILED       ProviderOAuthObservabilityProbeOutcome = 5
)

// Enum value maps for ProviderOAuthObservabilityProbeOutcome.
var (
	ProviderOAuthObservabilityProbeOutcome_name = map[int32]string{
		0: "PROVIDER_O_AUTH_OBSERVABILITY_PROBE_OUTCOME_UNSPECIFIED",
		1: "PROVIDER_O_AUTH_OBSERVABILITY_PROBE_OUTCOME_EXECUTED",
		2: "PROVIDER_O_AUTH_OBSERVABILITY_PROBE_OUTCOME_THROTTLED",
		3: "PROVIDER_O_AUTH_OBSERVABILITY_PROBE_OUTCOME_AUTH_BLOCKED",
		4: "PROVIDER_O_AUTH_OBSERVABILITY_PROBE_OUTCOME_UNSUPPORTED",
		5: "PROVIDER_O_AUTH_OBSERVABILITY_PROBE_OUTCOME_FAILED",
	}
	ProviderOAuthObservabilityProbeOutcome_value = map[string]int32{
		"PROVIDER_O_AUTH_OBSERVABILITY_PROBE_OUTCOME_UNSPECIFIED":  0,
		"PROVIDER_O_AUTH_OBSERVABILITY_PROBE_OUTCOME_EXECUTED":     1,
		"PROVIDER_O_AUTH_OBSERVABILITY_PROBE_OUTCOME_THROTTLED":    2,
		"PROVIDER_O_AUTH_OBSERVABILITY_PROBE_OUTCOME_AUTH_BLOCKED": 3,
		"PROVIDER_O_AUTH_OBSERVABILITY_PROBE_OUTCOME_UNSUPPORTED":  4,
		"PROVIDER_O_AUTH_OBSERVABILITY_PROBE_OUTCOME_FAILED":       5,
	}
)

func (x ProviderOAuthObservabilityProbeOutcome) Enum() *ProviderOAuthObservabilityProbeOutcome {
	p := new(ProviderOAuthObservabilityProbeOutcome)
	*p = x
	return p
}

func (x ProviderOAuthObservabilityProbeOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProviderOAuthObservabilityProbeOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_provider_v1_provider_shared_proto_enumTypes[3].Descriptor()
}

func (ProviderOAuthObservabilityProbeOutcome) Type() protoreflect.EnumType {
	return &file_platform_provider_v1_provider_shared_proto_enumTypes[3]
}

func (x ProviderOAuthObservabilityProbeOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProviderOAuthObservabilityProbeOutcome.Descriptor instead.
func (ProviderOAuthObservabilityProbeOutcome) EnumDescriptor() ([]byte, []int) {
	return file_platform_provider_v1_provider_shared_proto_rawDescGZIP(), []int{3}
}

// ProviderObservabilityProbeTrigger identifies what triggered a provider
// observability probe.
type ProviderObservabilityProbeTrigger int32

const (
	ProviderObservabilityProbeTrigger_PROVIDER_OBSERVABILITY_PROBE_TRIGGER_UNSPECIFIED ProviderObservabilityProbeTrigger = 0
	ProviderObservabilityProbeTrigger_PROVIDER_OBSERVABILITY_PROBE_TRIGGER_MANUAL      ProviderObservabilityProbeTrigger = 1
	ProviderObservabilityProbeTrigger_PROVIDER_OBSERVABILITY_PROBE_TRIGGER_CONNECT     ProviderObservabilityProbeTrigger = 2
	ProviderObservabilityProbeTrigger_PROVIDER_OBSERVABILITY_PROBE_TRIGGER_SCHEDULE    ProviderObservabilityProbeTrigger = 3
)

// Enum value maps for ProviderObservabilityProbeTrigger.
var (
	ProviderObservabilityProbeTrigger_name = map[int32]string{
		0: "PROVIDER_OBSERVABILITY_PROBE_TRIGGER_UNSPECIFIED",
		1: "PROVIDER_OBSERVABILITY_PROBE_TRIGGER_MANUAL",
		2: "PROVIDER_OBSERVABILITY_PROBE_TRIGGER_CONNECT",
		3: "PROVIDER_OBSERVABILITY_PROBE_TRIGGER_SCHEDULE",
	}
	ProviderObservabilityProbeTrigger_value = map[string]int32{
		"PROVIDER_OBSERVABILITY_PROBE_TRIGGER_UNSPECIFIED": 0,
		"PROVIDER_OBSERVABILITY_PROBE_TRIGGER_MANUAL":      1,
		"PROVIDER_OBSERVABILITY_PROBE_TRIGGER_CONNECT":     2,
		"PROVIDER_OBSERVABILITY_PROBE_TRIGGER_SCHEDULE":    3,
	}
)

func (x ProviderObservabilityProbeTrigger) Enum() *ProviderObservabilityProbeTrigger {
	p := new(ProviderObservabilityProbeTrigger)
	*p = x
	return p
}

func (x ProviderObservabilityProbeTrigger) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProviderObservabilityProbeTrigger) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_provider_v1_provider_shared_proto_enumTypes[4].Descriptor()
}

func (ProviderObservabilityProbeTrigger) Type() protoreflect.EnumType {
	return &file_platform_provider_v1_provider_shared_proto_enumTypes[4]
}

func (x ProviderObservabilityProbeTrigger) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProviderObservabilityProbeTrigger.Descriptor instead.
func (ProviderObservabilityProbeTrigger) EnumDescriptor() ([]byte, []int) {
	return file_platform_provider_v1_provider_shared_proto_rawDescGZIP(), []int{4}
}

// ProviderObservabilityProbeReason identifies the machine-readable reason for
// a decisive observability probe outcome.
type ProviderObservabilityProbeReason int32

const (
	ProviderObservabilityProbeReason_PROVIDER_OBSERVABILITY_PROBE_REASON_UNSPECIFIED          ProviderObservabilityProbeReason = 0
	ProviderObservabilityProbeReason_PROVIDER_OBSERVABILITY_PROBE_REASON_PLATFORM_UNAVAILABLE ProviderObservabilityProbeReason = 1
	ProviderObservabilityProbeReason_PROVIDER_OBSERVABILITY_PROBE_REASON_UPSTREAM_UNREACHABLE ProviderObservabilityProbeReason = 2
	ProviderObservabilityProbeReason_PROVIDER_OBSERVABILITY_PROBE_REASON_UPSTREAM_TIMEOUT     ProviderObservabilityProbeReason = 3
	ProviderObservabilityProbeReason_PROVIDER_OBSERVABILITY_PROBE_REASON_AUTH_BLOCKED         ProviderObservabilityProbeReason = 4
	ProviderObservabilityProbeReason_PROVIDER_OBSERVABILITY_PROBE_REASON_CREDENTIALS_MISSING  ProviderObservabilityProbeReason = 5
	ProviderObservabilityProbeReason_PROVIDER_OBSERVABILITY_PROBE_REASON_PROBE_FAILED         ProviderObservabilityProbeReason = 6
)

// Enum value maps for ProviderObservabilityProbeReason.
var (
	ProviderObservabilityProbeReason_name = map[int32]string{
		0: "PROVIDER_OBSERVABILITY_PROBE_REASON_UNSPECIFIED",
		1: "PROVIDER_OBSERVABILITY_PROBE_REASON_PLATFORM_UNAVAILABLE",
		2: "PROVIDER_OBSERVABILITY_PROBE_REASON_UPSTREAM_UNREACHABLE",
		3: "PROVIDER_OBSERVABILITY_PROBE_REASON_UPSTREAM_TIMEOUT",
		4: "PROVIDER_OBSERVABILITY_PROBE_REASON_AUTH_BLOCKED",
		5: "PROVIDER_OBSERVABILITY_PROBE_REASON_CREDENTIALS_MISSING",
		6: "PROVIDER_OBSERVABILITY_PROBE_REASON_PROBE_FAILED",
	}
	ProviderObservabilityProbeReason_value = map[string]int32{
		"PROVIDER_OBSERVABILITY_PROBE_REASON_UNSPECIFIED":          0,
		"PROVIDER_OBSERVABILITY_PROBE_REASON_PLATFORM_UNAVAILABLE": 1,
		"PROVIDER_OBSERVABILITY_PROBE_REASON_UPSTREAM_UNREACHABLE": 2,
		"PROVIDER_OBSERVABILITY_PROBE_REASON_UPSTREAM_TIMEOUT":     3,
		"PROVIDER_OBSERVABILITY_PROBE_REASON_AUTH_BLOCKED":         4,
		"PROVIDER_OBSERVABILITY_PROBE_REASON_CREDENTIALS_MISSING":  5,
		"PROVIDER_OBSERVABILITY_PROBE_REASON_PROBE_FAILED":         6,
	}
)

func (x ProviderObservabilityProbeReason) Enum() *ProviderObservabilityProbeReason {
	p := new(ProviderObservabilityProbeReason)
	*p = x
	return p
}

func (x ProviderObservabilityProbeReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProviderObservabilityProbeReason) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_provider_v1_provider_shared_proto_enumTypes[5].Descriptor()
}

func (ProviderObservabilityProbeReason) Type() protoreflect.EnumType {
	return &file_platform_provider_v1_provider_shared_proto_enumTypes[5]
}

func (x ProviderObservabilityProbeReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProviderObservabilityProbeReason.Descriptor instead.
func (ProviderObservabilityProbeReason) EnumDescriptor() ([]byte, []int) {
	return file_platform_provider_v1_provider_shared_proto_rawDescGZIP(), []int{5}
}

// ProviderStatusEventKind identifies the kind of a provider status event.
type ProviderStatusEventKind int32

const (
	ProviderStatusEventKind_PROVIDER_STATUS_EVENT_KIND_UNSPECIFIED ProviderStatusEventKind = 0
	ProviderStatusEventKind_PROVIDER_STATUS_EVENT_KIND_WORKFLOW    ProviderStatusEventKind = 1
	ProviderStatusEventKind_PROVIDER_STATUS_EVENT_KIND_STATUS      ProviderStatusEventKind = 2
)

// Enum value maps for ProviderStatusEventKind.
var (
	ProviderStatusEventKind_name = map[int32]string{
		0: "PROVIDER_STATUS_EVENT_KIND_UNSPECIFIED",
		1: "PROVIDER_STATUS_EVENT_KIND_WORKFLOW",
		2: "PROVIDER_STATUS_EVENT_KIND_STATUS",
	}
	ProviderStatusEventKind_value = map[string]int32{
		"PROVIDER_STATUS_EVENT_KIND_UNSPECIFIED": 0,
		"PROVIDER_STATUS_EVENT_KIND_WORKFLOW":    1,
		"PROVIDER_STATUS_EVENT_KIND_STATUS":      2,
	}
)

func (x ProviderStatusEventKind) Enum() *ProviderStatusEventKind {
	p := new(ProviderStatusEventKind)
	*p = x
	return p
}

func (x ProviderStatusEventKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProviderStatusEventKind) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_provider_v1_provider_shared_proto_enumTypes[6].Descriptor()
}

func (ProviderStatusEventKind) Type() protoreflect.EnumType {
	return &file_platform_provider_v1_provider_shared_proto_enumTypes[6]
}

func (x ProviderStatusEventKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProviderStatusEventKind.Descriptor instead.
func (ProviderStatusEventKind) EnumDescriptor() ([]byte, []int) {
	return file_platform_provider_v1_provider_shared_proto_rawDescGZIP(), []int{6}
}

// ProviderWorkflowPhase describes the lifecycle phase of a provider workflow.
type ProviderWorkflowPhase int32

const (
	ProviderWorkflowPhase_PROVIDER_WORKFLOW_PHASE_UNSPECIFIED ProviderWorkflowPhase = 0
	ProviderWorkflowPhase_PROVIDER_WORKFLOW_PHASE_PENDING     ProviderWorkflowPhase = 1
	ProviderWorkflowPhase_PROVIDER_WORKFLOW_PHASE_RUNNING     ProviderWorkflowPhase = 2
	ProviderWorkflowPhase_PROVIDER_WORKFLOW_PHASE_SUCCEEDED   ProviderWorkflowPhase = 3
	ProviderWorkflowPhase_PROVIDER_WORKFLOW_PHASE_FAILED      ProviderWorkflowPhase = 4
	ProviderWorkflowPhase_PROVIDER_WORKFLOW_PHASE_ERROR       ProviderWorkflowPhase = 5
	ProviderWorkflowPhase_PROVIDER_WORKFLOW_PHASE_CANCELED    ProviderWorkflowPhase = 6
)

// Enum value maps for ProviderWorkflowPhase.
var (
	ProviderWorkflowPhase_name = map[int32]string{
		0: "PROVIDER_WORKFLOW_PHASE_UNSPECIFIED",
		1: "PROVIDER_WORKFLOW_PHASE_PENDING",
		2: "PROVIDER_WORKFLOW_PHASE_RUNNING",
		3: "PROVIDER_WORKFLOW_PHASE_SUCCEEDED",
		4: "PROVIDER_WORKFLOW_PHASE_FAILED",
		5: "PROVIDER_WORKFLOW_PHASE_ERROR",
		6: "PROVIDER_WORKFLOW_PHASE_CANCELED",
	}
	ProviderWorkflowPhase_value = map[string]int32{
		"PROVIDER_WORKFLOW_PHASE_UNSPECIFIED": 0,
		"PROVIDER_WORKFLOW_PHASE_PENDING":     1,
		"PROVIDER_WORKFLOW_PHASE_RUNNING":     2,
		"PROVIDER_WORKFLOW_PHASE_SUCCEEDED":   3,
		"PROVIDER_WORKFLOW_PHASE_FAILED":      4,
		"PROVIDER_WORKFLOW_PHASE_ERROR":       5,
		"PROVIDER_WORKFLOW_PHASE_CANCELED":    6,
	}
)

func (x ProviderWorkflowPhase) Enum() *ProviderWorkflowPhase {
	p := new(ProviderWorkflowPhase)
	*p = x
	return p
}

func (x ProviderWorkflowPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProviderWorkflowPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_platform_provider_v1_provider_shared_proto_enumTypes[7].Descriptor()
}

func (ProviderWorkflowPhase) Type() protoreflect.EnumType {
	return &file_platform_provider_v1_provider_shared_proto_enumTypes[7]
}

func (x ProviderWorkflowPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProviderWorkflowPhase.Descriptor instead.
func (ProviderWorkflowPhase) EnumDescriptor() ([]byte, []int) {
	return file_platform_provider_v1_provider_shared_proto_rawDescGZIP(), []int{7}
}

var File_platform_provider_v1_provider_shared_proto protoreflect.FileDescriptor

const file_platform_provider_v1_provider_shared_proto_rawDesc = "" +
	"\n" +
	"*platform/provider/v1/provider_shared.proto\x12\x14platform.provider.v1*\xbf\x01\n" +
	"\rProviderPhase\x12\x1e\n" +
	"\x1aPROVIDER_PHASE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PROVIDER_PHASE_READY\x10\x01\x12!\n" +
	"\x1dPROVIDER_PHASE_INVALID_CONFIG\x10\x02\x12\x1d\n" +
	"\x19PROVIDER_PHASE_REFRESHING\x10\x03\x12\x18\n" +
	"\x14PROVIDER_PHASE_STALE\x10\x04\x12\x18\n" +
	"\x14PROVIDER_PHASE_ERROR\x10\x05*\x8c\x03\n" +
	"\x1bProviderConnectSessionPhase\x12.\n" +
	"*PROVIDER_CONNECT_SESSION_PHASE_UNSPECIFIED\x10\x00\x12*\n" +
	"&PROVIDER_CONNECT_SESSION_PHASE_PENDING\x10\x01\x120\n" +
	",PROVIDER_CONNECT_SESSION_PHASE_AWAITING_USER\x10\x02\x12-\n" +
	")PROVIDER_CONNECT_SESSION_PHASE_PROCESSING\x10\x03\x12,\n" +
	"(PROVIDER_CONNECT_SESSION_PHASE_SUCCEEDED\x10\x04\x12)\n" +
	"%PROVIDER_CONNECT_SESSION_PHASE_FAILED\x10\x05\x12*\n" +
	"&PROVIDER_CONNECT_SESSION_PHASE_EXPIRED\x10\x06\x12+\n" +
	"'PROVIDER_CONNECT_SESSION_PHASE_CANCELED\x10\a*|\n" +
	"\x11ProviderAddMethod\x12#\n" +
	"\x1fPROVIDER_ADD_METHOD_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bPROVIDER_ADD_METHOD_API_KEY\x10\x01\x12!\n" +
	"\x1dPROVIDER_ADD_METHOD_CLI_OAUTH\x10\x02*\x8d\x03\n" +
	"&ProviderOAuthObservabilityProbeOutcome\x12;\n" +
	"7PROVIDER_O_AUTH_OBSERVABILITY_PROBE_OUTCOME_UNSPECIFIED\x10\x00\x128\n" +
	"4PROVIDER_O_AUTH_OBSERVABILITY_PROBE_OUTCOME_EXECUTED\x10\x01\x129\n" +
	"5PROVIDER_O_AUTH_OBSERVABILITY_PROBE_OUTCOME_THROTTLED\x10\x02\x12<\n" +
	"8PROVIDER_O_AUTH_OBSERVABILITY_PROBE_OUTCOME_AUTH_BLOCKED\x10\x03\x12;\n" +
	"7PROVIDER_O_AUTH_OBSERVABILITY_PROBE_OUTCOME_UNSUPPORTED\x10\x04\x126\n" +
	"2PROVIDER_O_AUTH_OBSERVABILITY_PROBE_OUTCOME_FAILED\x10\x05*\xef\x01\n" +
	"!ProviderObservabilityProbeTrigger\x124\n" +
	"0PROVIDER_OBSERVABILITY_PROBE_TRIGGER_UNSPECIFIED\x10\x00\x12/\n" +
	"+PROVIDER_OBSERVABILITY_PROBE_TRIGGER_MANUAL\x10\x01\x120\n" +
	",PROVIDER_OBSERVABILITY_PROBE_TRIGGER_CONNECT\x10\x02\x121\n" +
	"-PROVIDER_OBSERVABILITY_PROBE_TRIGGER_SCHEDULE\x10\x03*\xb6\x03\n" +
	" ProviderObservabilityProbeReason\x123\n" +
	"/PROVIDER_OBSERVABILITY_PROBE_REASON_UNSPECIFIED\x10\x00\x12<\n" +
	"8PROVIDER_OBSERVABILITY_PROBE_REASON_PLATFORM_UNAVAILABLE\x10\x01\x12<\n" +
	"8PROVIDER_OBSERVABILITY_PROBE_REASON_UPSTREAM_UNREACHABLE\x10\x02\x128\n" +
	"4PROVIDER_OBSERVABILITY_PROBE_REASON_UPSTREAM_TIMEOUT\x10\x03\x124\n" +
	"0PROVIDER_OBSERVABILITY_PROBE_REASON_AUTH_BLOCKED\x10\x04\x12;\n" +
	"7PROVIDER_OBSERVABILITY_PROBE_REASON_CREDENTIALS_MISSING\x10\x05\x124\n" +
	"0PROVIDER_OBSERVABILITY_PROBE_REASON_PROBE_FAILED\x10\x06*\x95\x01\n" +
	"\x17ProviderStatusEventKind\x12*\n" +
	"&PROVIDER_STATUS_EVENT_KIND_UNSPECIFIED\x10\x00\x12'\n" +
	"#PROVIDER_STATUS_EVENT_KIND_WORKFLOW\x10\x01\x12%\n" +
	"!PROVIDER_STATUS_EVENT_KIND_STATUS\x10\x02*\x9e\x02\n" +
	"\x15ProviderWorkflowPhase\x12'\n" +
	"#PROVIDER_WORKFLOW_PHASE_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fPROVIDER_WORKFLOW_PHASE_PENDING\x10\x01\x12#\n" +
	"\x1fPROVIDER_WORKFLOW_PHASE_RUNNING\x10\x02\x12%\n" +
	"!PROVIDER_WORKFLOW_PHASE_SUCCEEDED\x10\x03\x12\"\n" +
	"\x1ePROVIDER_WORKFLOW_PHASE_FAILED\x10\x04\x12!\n" +
	"\x1dPROVIDER_WORKFLOW_PHASE_ERROR\x10\x05\x12$\n" +
	" PROVIDER_WORKFLOW_PHASE_CANCELED\x10\x06BGZEcode-code.internal/go-contract/platform/provider/v1;providerservicev1b\x06proto3"

var (
	file_platform_provider_v1_provider_shared_proto_rawDescOnce sync.Once
	file_platform_provider_v1_provider_shared_proto_rawDescData []byte
)

func file_platform_provider_v1_provider_shared_proto_rawDescGZIP() []byte {
	file_platform_provider_v1_provider_shared_proto_rawDescOnce.Do(func() {
		file_platform_provider_v1_provider_shared_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_platform_provider_v1_provider_shared_proto_rawDesc), len(file_platform_provider_v1_provider_shared_proto_rawDesc)))
	})
	return file_platform_provider_v1_provider_shared_proto_rawDescData
}

var file_platform_provider_v1_provider_shared_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_platform_provider_v1_provider_shared_proto_goTypes = []any{
	(ProviderPhase)(0),                          // 0: platform.provider.v1.ProviderPhase
	(ProviderConnectSessionPhase)(0),            // 1: platform.provider.v1.ProviderConnectSessionPhase
	(ProviderAddMethod)(0),                      // 2: platform.provider.v1.ProviderAddMethod
	(ProviderOAuthObservabilityProbeOutcome)(0), // 3: platform.provider.v1.ProviderOAuthObservabilityProbeOutcome
	(ProviderObservabilityProbeTrigger)(0),      // 4: platform.provider.v1.ProviderObservabilityProbeTrigger
	(ProviderObservabilityProbeReason)(0),       // 5: platform.provider.v1.ProviderObservabilityProbeReason
	(ProviderStatusEventKind)(0),                // 6: platform.provider.v1.ProviderStatusEventKind
	(ProviderWorkflowPhase)(0),                  // 7: platform.provider.v1.ProviderWorkflowPhase
}
var file_platform_provider_v1_provider_shared_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_platform_provider_v1_provider_shared_proto_init() }
func file_platform_provider_v1_provider_shared_proto_init() {
	if File_platform_provider_v1_provider_shared_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_platform_provider_v1_provider_shared_proto_rawDesc), len(file_platform_provider_v1_provider_shared_proto_rawDesc)),
			NumEnums:      8,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_platform_provider_v1_provider_shared_proto_goTypes,
		DependencyIndexes: file_platform_provider_v1_provider_shared_proto_depIdxs,
		EnumInfos:         file_platform_provider_v1_provider_shared_proto_enumTypes,
	}.Build()
	File_platform_provider_v1_provider_shared_proto = out.File
	file_platform_provider_v1_provider_shared_proto_goTypes = nil
	file_platform_provider_v1_provider_shared_proto_depIdxs = nil
}
