// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: platform/orchestration/v1/provider_orchestration_service.proto

package orchestrationv1connect

import (
	v1 "code-code.internal/go-contract/platform/management/v1"
	v11 "code-code.internal/go-contract/platform/orchestration/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ProviderOrchestrationServiceName is the fully-qualified name of the ProviderOrchestrationService
	// service.
	ProviderOrchestrationServiceName = "platform.orchestration.v1.ProviderOrchestrationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ProviderOrchestrationServiceConnectProviderProcedure is the fully-qualified name of the
	// ProviderOrchestrationService's ConnectProvider RPC.
	ProviderOrchestrationServiceConnectProviderProcedure = "/platform.orchestration.v1.ProviderOrchestrationService/ConnectProvider"
	// ProviderOrchestrationServiceGetProviderConnectSessionProcedure is the fully-qualified name of the
	// ProviderOrchestrationService's GetProviderConnectSession RPC.
	ProviderOrchestrationServiceGetProviderConnectSessionProcedure = "/platform.orchestration.v1.ProviderOrchestrationService/GetProviderConnectSession"
	// ProviderOrchestrationServiceUpdateProviderAuthenticationProcedure is the fully-qualified name of
	// the ProviderOrchestrationService's UpdateProviderAuthentication RPC.
	ProviderOrchestrationServiceUpdateProviderAuthenticationProcedure = "/platform.orchestration.v1.ProviderOrchestrationService/UpdateProviderAuthentication"
	// ProviderOrchestrationServiceUpdateProviderObservabilityAuthenticationProcedure is the
	// fully-qualified name of the ProviderOrchestrationService's
	// UpdateProviderObservabilityAuthentication RPC.
	ProviderOrchestrationServiceUpdateProviderObservabilityAuthenticationProcedure = "/platform.orchestration.v1.ProviderOrchestrationService/UpdateProviderObservabilityAuthentication"
	// ProviderOrchestrationServiceProbeProviderObservabilityProcedure is the fully-qualified name of
	// the ProviderOrchestrationService's ProbeProviderObservability RPC.
	ProviderOrchestrationServiceProbeProviderObservabilityProcedure = "/platform.orchestration.v1.ProviderOrchestrationService/ProbeProviderObservability"
	// ProviderOrchestrationServiceProbeProviderModelCatalogProcedure is the fully-qualified name of the
	// ProviderOrchestrationService's ProbeProviderModelCatalog RPC.
	ProviderOrchestrationServiceProbeProviderModelCatalogProcedure = "/platform.orchestration.v1.ProviderOrchestrationService/ProbeProviderModelCatalog"
)

// ProviderOrchestrationServiceClient is a client for the
// platform.orchestration.v1.ProviderOrchestrationService service.
type ProviderOrchestrationServiceClient interface {
	ConnectProvider(context.Context, *v1.ConnectProviderRequest) (*v1.ConnectProviderResponse, error)
	GetProviderConnectSession(context.Context, *v1.GetProviderConnectSessionRequest) (*v1.GetProviderConnectSessionResponse, error)
	UpdateProviderAuthentication(context.Context, *v1.UpdateProviderAuthenticationRequest) (*v1.UpdateProviderAuthenticationResponse, error)
	UpdateProviderObservabilityAuthentication(context.Context, *v1.UpdateProviderObservabilityAuthenticationRequest) (*v1.UpdateProviderObservabilityAuthenticationResponse, error)
	ProbeProviderObservability(context.Context, *v1.ProbeProviderObservabilityRequest) (*v1.ProbeProviderObservabilityResponse, error)
	ProbeProviderModelCatalog(context.Context, *v1.ProbeProviderModelCatalogRequest) (*v1.ProbeProviderModelCatalogResponse, error)
}

// NewProviderOrchestrationServiceClient constructs a client for the
// platform.orchestration.v1.ProviderOrchestrationService service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProviderOrchestrationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProviderOrchestrationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	providerOrchestrationServiceMethods := v11.File_platform_orchestration_v1_provider_orchestration_service_proto.Services().ByName("ProviderOrchestrationService").Methods()
	return &providerOrchestrationServiceClient{
		connectProvider: connect.NewClient[v1.ConnectProviderRequest, v1.ConnectProviderResponse](
			httpClient,
			baseURL+ProviderOrchestrationServiceConnectProviderProcedure,
			connect.WithSchema(providerOrchestrationServiceMethods.ByName("ConnectProvider")),
			connect.WithClientOptions(opts...),
		),
		getProviderConnectSession: connect.NewClient[v1.GetProviderConnectSessionRequest, v1.GetProviderConnectSessionResponse](
			httpClient,
			baseURL+ProviderOrchestrationServiceGetProviderConnectSessionProcedure,
			connect.WithSchema(providerOrchestrationServiceMethods.ByName("GetProviderConnectSession")),
			connect.WithClientOptions(opts...),
		),
		updateProviderAuthentication: connect.NewClient[v1.UpdateProviderAuthenticationRequest, v1.UpdateProviderAuthenticationResponse](
			httpClient,
			baseURL+ProviderOrchestrationServiceUpdateProviderAuthenticationProcedure,
			connect.WithSchema(providerOrchestrationServiceMethods.ByName("UpdateProviderAuthentication")),
			connect.WithClientOptions(opts...),
		),
		updateProviderObservabilityAuthentication: connect.NewClient[v1.UpdateProviderObservabilityAuthenticationRequest, v1.UpdateProviderObservabilityAuthenticationResponse](
			httpClient,
			baseURL+ProviderOrchestrationServiceUpdateProviderObservabilityAuthenticationProcedure,
			connect.WithSchema(providerOrchestrationServiceMethods.ByName("UpdateProviderObservabilityAuthentication")),
			connect.WithClientOptions(opts...),
		),
		probeProviderObservability: connect.NewClient[v1.ProbeProviderObservabilityRequest, v1.ProbeProviderObservabilityResponse](
			httpClient,
			baseURL+ProviderOrchestrationServiceProbeProviderObservabilityProcedure,
			connect.WithSchema(providerOrchestrationServiceMethods.ByName("ProbeProviderObservability")),
			connect.WithClientOptions(opts...),
		),
		probeProviderModelCatalog: connect.NewClient[v1.ProbeProviderModelCatalogRequest, v1.ProbeProviderModelCatalogResponse](
			httpClient,
			baseURL+ProviderOrchestrationServiceProbeProviderModelCatalogProcedure,
			connect.WithSchema(providerOrchestrationServiceMethods.ByName("ProbeProviderModelCatalog")),
			connect.WithClientOptions(opts...),
		),
	}
}

// providerOrchestrationServiceClient implements ProviderOrchestrationServiceClient.
type providerOrchestrationServiceClient struct {
	connectProvider                           *connect.Client[v1.ConnectProviderRequest, v1.ConnectProviderResponse]
	getProviderConnectSession                 *connect.Client[v1.GetProviderConnectSessionRequest, v1.GetProviderConnectSessionResponse]
	updateProviderAuthentication              *connect.Client[v1.UpdateProviderAuthenticationRequest, v1.UpdateProviderAuthenticationResponse]
	updateProviderObservabilityAuthentication *connect.Client[v1.UpdateProviderObservabilityAuthenticationRequest, v1.UpdateProviderObservabilityAuthenticationResponse]
	probeProviderObservability                *connect.Client[v1.ProbeProviderObservabilityRequest, v1.ProbeProviderObservabilityResponse]
	probeProviderModelCatalog                 *connect.Client[v1.ProbeProviderModelCatalogRequest, v1.ProbeProviderModelCatalogResponse]
}

// ConnectProvider calls platform.orchestration.v1.ProviderOrchestrationService.ConnectProvider.
func (c *providerOrchestrationServiceClient) ConnectProvider(ctx context.Context, req *v1.ConnectProviderRequest) (*v1.ConnectProviderResponse, error) {
	response, err := c.connectProvider.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// GetProviderConnectSession calls
// platform.orchestration.v1.ProviderOrchestrationService.GetProviderConnectSession.
func (c *providerOrchestrationServiceClient) GetProviderConnectSession(ctx context.Context, req *v1.GetProviderConnectSessionRequest) (*v1.GetProviderConnectSessionResponse, error) {
	response, err := c.getProviderConnectSession.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// UpdateProviderAuthentication calls
// platform.orchestration.v1.ProviderOrchestrationService.UpdateProviderAuthentication.
func (c *providerOrchestrationServiceClient) UpdateProviderAuthentication(ctx context.Context, req *v1.UpdateProviderAuthenticationRequest) (*v1.UpdateProviderAuthenticationResponse, error) {
	response, err := c.updateProviderAuthentication.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// UpdateProviderObservabilityAuthentication calls
// platform.orchestration.v1.ProviderOrchestrationService.UpdateProviderObservabilityAuthentication.
func (c *providerOrchestrationServiceClient) UpdateProviderObservabilityAuthentication(ctx context.Context, req *v1.UpdateProviderObservabilityAuthenticationRequest) (*v1.UpdateProviderObservabilityAuthenticationResponse, error) {
	response, err := c.updateProviderObservabilityAuthentication.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ProbeProviderObservability calls
// platform.orchestration.v1.ProviderOrchestrationService.ProbeProviderObservability.
func (c *providerOrchestrationServiceClient) ProbeProviderObservability(ctx context.Context, req *v1.ProbeProviderObservabilityRequest) (*v1.ProbeProviderObservabilityResponse, error) {
	response, err := c.probeProviderObservability.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ProbeProviderModelCatalog calls
// platform.orchestration.v1.ProviderOrchestrationService.ProbeProviderModelCatalog.
func (c *providerOrchestrationServiceClient) ProbeProviderModelCatalog(ctx context.Context, req *v1.ProbeProviderModelCatalogRequest) (*v1.ProbeProviderModelCatalogResponse, error) {
	response, err := c.probeProviderModelCatalog.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ProviderOrchestrationServiceHandler is an implementation of the
// platform.orchestration.v1.ProviderOrchestrationService service.
type ProviderOrchestrationServiceHandler interface {
	ConnectProvider(context.Context, *v1.ConnectProviderRequest) (*v1.ConnectProviderResponse, error)
	GetProviderConnectSession(context.Context, *v1.GetProviderConnectSessionRequest) (*v1.GetProviderConnectSessionResponse, error)
	UpdateProviderAuthentication(context.Context, *v1.UpdateProviderAuthenticationRequest) (*v1.UpdateProviderAuthenticationResponse, error)
	UpdateProviderObservabilityAuthentication(context.Context, *v1.UpdateProviderObservabilityAuthenticationRequest) (*v1.UpdateProviderObservabilityAuthenticationResponse, error)
	ProbeProviderObservability(context.Context, *v1.ProbeProviderObservabilityRequest) (*v1.ProbeProviderObservabilityResponse, error)
	ProbeProviderModelCatalog(context.Context, *v1.ProbeProviderModelCatalogRequest) (*v1.ProbeProviderModelCatalogResponse, error)
}

// NewProviderOrchestrationServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProviderOrchestrationServiceHandler(svc ProviderOrchestrationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	providerOrchestrationServiceMethods := v11.File_platform_orchestration_v1_provider_orchestration_service_proto.Services().ByName("ProviderOrchestrationService").Methods()
	providerOrchestrationServiceConnectProviderHandler := connect.NewUnaryHandlerSimple(
		ProviderOrchestrationServiceConnectProviderProcedure,
		svc.ConnectProvider,
		connect.WithSchema(providerOrchestrationServiceMethods.ByName("ConnectProvider")),
		connect.WithHandlerOptions(opts...),
	)
	providerOrchestrationServiceGetProviderConnectSessionHandler := connect.NewUnaryHandlerSimple(
		ProviderOrchestrationServiceGetProviderConnectSessionProcedure,
		svc.GetProviderConnectSession,
		connect.WithSchema(providerOrchestrationServiceMethods.ByName("GetProviderConnectSession")),
		connect.WithHandlerOptions(opts...),
	)
	providerOrchestrationServiceUpdateProviderAuthenticationHandler := connect.NewUnaryHandlerSimple(
		ProviderOrchestrationServiceUpdateProviderAuthenticationProcedure,
		svc.UpdateProviderAuthentication,
		connect.WithSchema(providerOrchestrationServiceMethods.ByName("UpdateProviderAuthentication")),
		connect.WithHandlerOptions(opts...),
	)
	providerOrchestrationServiceUpdateProviderObservabilityAuthenticationHandler := connect.NewUnaryHandlerSimple(
		ProviderOrchestrationServiceUpdateProviderObservabilityAuthenticationProcedure,
		svc.UpdateProviderObservabilityAuthentication,
		connect.WithSchema(providerOrchestrationServiceMethods.ByName("UpdateProviderObservabilityAuthentication")),
		connect.WithHandlerOptions(opts...),
	)
	providerOrchestrationServiceProbeProviderObservabilityHandler := connect.NewUnaryHandlerSimple(
		ProviderOrchestrationServiceProbeProviderObservabilityProcedure,
		svc.ProbeProviderObservability,
		connect.WithSchema(providerOrchestrationServiceMethods.ByName("ProbeProviderObservability")),
		connect.WithHandlerOptions(opts...),
	)
	providerOrchestrationServiceProbeProviderModelCatalogHandler := connect.NewUnaryHandlerSimple(
		ProviderOrchestrationServiceProbeProviderModelCatalogProcedure,
		svc.ProbeProviderModelCatalog,
		connect.WithSchema(providerOrchestrationServiceMethods.ByName("ProbeProviderModelCatalog")),
		connect.WithHandlerOptions(opts...),
	)
	return "/platform.orchestration.v1.ProviderOrchestrationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProviderOrchestrationServiceConnectProviderProcedure:
			providerOrchestrationServiceConnectProviderHandler.ServeHTTP(w, r)
		case ProviderOrchestrationServiceGetProviderConnectSessionProcedure:
			providerOrchestrationServiceGetProviderConnectSessionHandler.ServeHTTP(w, r)
		case ProviderOrchestrationServiceUpdateProviderAuthenticationProcedure:
			providerOrchestrationServiceUpdateProviderAuthenticationHandler.ServeHTTP(w, r)
		case ProviderOrchestrationServiceUpdateProviderObservabilityAuthenticationProcedure:
			providerOrchestrationServiceUpdateProviderObservabilityAuthenticationHandler.ServeHTTP(w, r)
		case ProviderOrchestrationServiceProbeProviderObservabilityProcedure:
			providerOrchestrationServiceProbeProviderObservabilityHandler.ServeHTTP(w, r)
		case ProviderOrchestrationServiceProbeProviderModelCatalogProcedure:
			providerOrchestrationServiceProbeProviderModelCatalogHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProviderOrchestrationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProviderOrchestrationServiceHandler struct{}

func (UnimplementedProviderOrchestrationServiceHandler) ConnectProvider(context.Context, *v1.ConnectProviderRequest) (*v1.ConnectProviderResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.orchestration.v1.ProviderOrchestrationService.ConnectProvider is not implemented"))
}

func (UnimplementedProviderOrchestrationServiceHandler) GetProviderConnectSession(context.Context, *v1.GetProviderConnectSessionRequest) (*v1.GetProviderConnectSessionResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.orchestration.v1.ProviderOrchestrationService.GetProviderConnectSession is not implemented"))
}

func (UnimplementedProviderOrchestrationServiceHandler) UpdateProviderAuthentication(context.Context, *v1.UpdateProviderAuthenticationRequest) (*v1.UpdateProviderAuthenticationResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.orchestration.v1.ProviderOrchestrationService.UpdateProviderAuthentication is not implemented"))
}

func (UnimplementedProviderOrchestrationServiceHandler) UpdateProviderObservabilityAuthentication(context.Context, *v1.UpdateProviderObservabilityAuthenticationRequest) (*v1.UpdateProviderObservabilityAuthenticationResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.orchestration.v1.ProviderOrchestrationService.UpdateProviderObservabilityAuthentication is not implemented"))
}

func (UnimplementedProviderOrchestrationServiceHandler) ProbeProviderObservability(context.Context, *v1.ProbeProviderObservabilityRequest) (*v1.ProbeProviderObservabilityResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.orchestration.v1.ProviderOrchestrationService.ProbeProviderObservability is not implemented"))
}

func (UnimplementedProviderOrchestrationServiceHandler) ProbeProviderModelCatalog(context.Context, *v1.ProbeProviderModelCatalogRequest) (*v1.ProbeProviderModelCatalogResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.orchestration.v1.ProviderOrchestrationService.ProbeProviderModelCatalog is not implemented"))
}
