// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: platform/provider/v1/provider_service.proto

package providerservicev1connect

import (
	v1 "code-code.internal/go-contract/platform/provider/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ProviderServiceName is the fully-qualified name of the ProviderService service.
	ProviderServiceName = "platform.provider.v1.ProviderService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ProviderServiceListProviderSurfacesProcedure is the fully-qualified name of the ProviderService's
	// ListProviderSurfaces RPC.
	ProviderServiceListProviderSurfacesProcedure = "/platform.provider.v1.ProviderService/ListProviderSurfaces"
	// ProviderServiceListProvidersProcedure is the fully-qualified name of the ProviderService's
	// ListProviders RPC.
	ProviderServiceListProvidersProcedure = "/platform.provider.v1.ProviderService/ListProviders"
	// ProviderServiceCreateProviderProcedure is the fully-qualified name of the ProviderService's
	// CreateProvider RPC.
	ProviderServiceCreateProviderProcedure = "/platform.provider.v1.ProviderService/CreateProvider"
	// ProviderServiceUpdateProviderProcedure is the fully-qualified name of the ProviderService's
	// UpdateProvider RPC.
	ProviderServiceUpdateProviderProcedure = "/platform.provider.v1.ProviderService/UpdateProvider"
	// ProviderServiceDeleteProviderProcedure is the fully-qualified name of the ProviderService's
	// DeleteProvider RPC.
	ProviderServiceDeleteProviderProcedure = "/platform.provider.v1.ProviderService/DeleteProvider"
	// ProviderServiceProbeProviderObservabilityProcedure is the fully-qualified name of the
	// ProviderService's ProbeProviderObservability RPC.
	ProviderServiceProbeProviderObservabilityProcedure = "/platform.provider.v1.ProviderService/ProbeProviderObservability"
	// ProviderServiceWatchProviderStatusEventsProcedure is the fully-qualified name of the
	// ProviderService's WatchProviderStatusEvents RPC.
	ProviderServiceWatchProviderStatusEventsProcedure = "/platform.provider.v1.ProviderService/WatchProviderStatusEvents"
	// ProviderServiceListVendorsProcedure is the fully-qualified name of the ProviderService's
	// ListVendors RPC.
	ProviderServiceListVendorsProcedure = "/platform.provider.v1.ProviderService/ListVendors"
	// ProviderServiceListCLIDefinitionsProcedure is the fully-qualified name of the ProviderService's
	// ListCLIDefinitions RPC.
	ProviderServiceListCLIDefinitionsProcedure = "/platform.provider.v1.ProviderService/ListCLIDefinitions"
	// ProviderServiceListTemplatesProcedure is the fully-qualified name of the ProviderService's
	// ListTemplates RPC.
	ProviderServiceListTemplatesProcedure = "/platform.provider.v1.ProviderService/ListTemplates"
	// ProviderServiceApplyTemplateProcedure is the fully-qualified name of the ProviderService's
	// ApplyTemplate RPC.
	ProviderServiceApplyTemplateProcedure = "/platform.provider.v1.ProviderService/ApplyTemplate"
)

// ProviderServiceClient is a client for the platform.provider.v1.ProviderService service.
type ProviderServiceClient interface {
	ListProviderSurfaces(context.Context, *v1.ListProviderSurfacesRequest) (*v1.ListProviderSurfacesResponse, error)
	ListProviders(context.Context, *v1.ListProvidersRequest) (*v1.ListProvidersResponse, error)
	CreateProvider(context.Context, *v1.CreateProviderRequest) (*v1.CreateProviderResponse, error)
	UpdateProvider(context.Context, *v1.UpdateProviderRequest) (*v1.UpdateProviderResponse, error)
	DeleteProvider(context.Context, *v1.DeleteProviderRequest) (*v1.DeleteProviderResponse, error)
	ProbeProviderObservability(context.Context, *v1.ProbeProviderObservabilityRequest) (*v1.ProbeProviderObservabilityResponse, error)
	WatchProviderStatusEvents(context.Context, *v1.WatchProviderStatusEventsRequest) (*connect.ServerStreamForClient[v1.WatchProviderStatusEventsResponse], error)
	ListVendors(context.Context, *v1.ListVendorsRequest) (*v1.ListVendorsResponse, error)
	ListCLIDefinitions(context.Context, *v1.ListCLIDefinitionsRequest) (*v1.ListCLIDefinitionsResponse, error)
	ListTemplates(context.Context, *v1.ListTemplatesRequest) (*v1.ListTemplatesResponse, error)
	ApplyTemplate(context.Context, *v1.ApplyTemplateRequest) (*v1.ApplyTemplateResponse, error)
}

// NewProviderServiceClient constructs a client for the platform.provider.v1.ProviderService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProviderServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProviderServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	providerServiceMethods := v1.File_platform_provider_v1_provider_service_proto.Services().ByName("ProviderService").Methods()
	return &providerServiceClient{
		listProviderSurfaces: connect.NewClient[v1.ListProviderSurfacesRequest, v1.ListProviderSurfacesResponse](
			httpClient,
			baseURL+ProviderServiceListProviderSurfacesProcedure,
			connect.WithSchema(providerServiceMethods.ByName("ListProviderSurfaces")),
			connect.WithClientOptions(opts...),
		),
		listProviders: connect.NewClient[v1.ListProvidersRequest, v1.ListProvidersResponse](
			httpClient,
			baseURL+ProviderServiceListProvidersProcedure,
			connect.WithSchema(providerServiceMethods.ByName("ListProviders")),
			connect.WithClientOptions(opts...),
		),
		createProvider: connect.NewClient[v1.CreateProviderRequest, v1.CreateProviderResponse](
			httpClient,
			baseURL+ProviderServiceCreateProviderProcedure,
			connect.WithSchema(providerServiceMethods.ByName("CreateProvider")),
			connect.WithClientOptions(opts...),
		),
		updateProvider: connect.NewClient[v1.UpdateProviderRequest, v1.UpdateProviderResponse](
			httpClient,
			baseURL+ProviderServiceUpdateProviderProcedure,
			connect.WithSchema(providerServiceMethods.ByName("UpdateProvider")),
			connect.WithClientOptions(opts...),
		),
		deleteProvider: connect.NewClient[v1.DeleteProviderRequest, v1.DeleteProviderResponse](
			httpClient,
			baseURL+ProviderServiceDeleteProviderProcedure,
			connect.WithSchema(providerServiceMethods.ByName("DeleteProvider")),
			connect.WithClientOptions(opts...),
		),
		probeProviderObservability: connect.NewClient[v1.ProbeProviderObservabilityRequest, v1.ProbeProviderObservabilityResponse](
			httpClient,
			baseURL+ProviderServiceProbeProviderObservabilityProcedure,
			connect.WithSchema(providerServiceMethods.ByName("ProbeProviderObservability")),
			connect.WithClientOptions(opts...),
		),
		watchProviderStatusEvents: connect.NewClient[v1.WatchProviderStatusEventsRequest, v1.WatchProviderStatusEventsResponse](
			httpClient,
			baseURL+ProviderServiceWatchProviderStatusEventsProcedure,
			connect.WithSchema(providerServiceMethods.ByName("WatchProviderStatusEvents")),
			connect.WithClientOptions(opts...),
		),
		listVendors: connect.NewClient[v1.ListVendorsRequest, v1.ListVendorsResponse](
			httpClient,
			baseURL+ProviderServiceListVendorsProcedure,
			connect.WithSchema(providerServiceMethods.ByName("ListVendors")),
			connect.WithClientOptions(opts...),
		),
		listCLIDefinitions: connect.NewClient[v1.ListCLIDefinitionsRequest, v1.ListCLIDefinitionsResponse](
			httpClient,
			baseURL+ProviderServiceListCLIDefinitionsProcedure,
			connect.WithSchema(providerServiceMethods.ByName("ListCLIDefinitions")),
			connect.WithClientOptions(opts...),
		),
		listTemplates: connect.NewClient[v1.ListTemplatesRequest, v1.ListTemplatesResponse](
			httpClient,
			baseURL+ProviderServiceListTemplatesProcedure,
			connect.WithSchema(providerServiceMethods.ByName("ListTemplates")),
			connect.WithClientOptions(opts...),
		),
		applyTemplate: connect.NewClient[v1.ApplyTemplateRequest, v1.ApplyTemplateResponse](
			httpClient,
			baseURL+ProviderServiceApplyTemplateProcedure,
			connect.WithSchema(providerServiceMethods.ByName("ApplyTemplate")),
			connect.WithClientOptions(opts...),
		),
	}
}

// providerServiceClient implements ProviderServiceClient.
type providerServiceClient struct {
	listProviderSurfaces       *connect.Client[v1.ListProviderSurfacesRequest, v1.ListProviderSurfacesResponse]
	listProviders              *connect.Client[v1.ListProvidersRequest, v1.ListProvidersResponse]
	createProvider             *connect.Client[v1.CreateProviderRequest, v1.CreateProviderResponse]
	updateProvider             *connect.Client[v1.UpdateProviderRequest, v1.UpdateProviderResponse]
	deleteProvider             *connect.Client[v1.DeleteProviderRequest, v1.DeleteProviderResponse]
	probeProviderObservability *connect.Client[v1.ProbeProviderObservabilityRequest, v1.ProbeProviderObservabilityResponse]
	watchProviderStatusEvents  *connect.Client[v1.WatchProviderStatusEventsRequest, v1.WatchProviderStatusEventsResponse]
	listVendors                *connect.Client[v1.ListVendorsRequest, v1.ListVendorsResponse]
	listCLIDefinitions         *connect.Client[v1.ListCLIDefinitionsRequest, v1.ListCLIDefinitionsResponse]
	listTemplates              *connect.Client[v1.ListTemplatesRequest, v1.ListTemplatesResponse]
	applyTemplate              *connect.Client[v1.ApplyTemplateRequest, v1.ApplyTemplateResponse]
}

// ListProviderSurfaces calls platform.provider.v1.ProviderService.ListProviderSurfaces.
func (c *providerServiceClient) ListProviderSurfaces(ctx context.Context, req *v1.ListProviderSurfacesRequest) (*v1.ListProviderSurfacesResponse, error) {
	response, err := c.listProviderSurfaces.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListProviders calls platform.provider.v1.ProviderService.ListProviders.
func (c *providerServiceClient) ListProviders(ctx context.Context, req *v1.ListProvidersRequest) (*v1.ListProvidersResponse, error) {
	response, err := c.listProviders.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// CreateProvider calls platform.provider.v1.ProviderService.CreateProvider.
func (c *providerServiceClient) CreateProvider(ctx context.Context, req *v1.CreateProviderRequest) (*v1.CreateProviderResponse, error) {
	response, err := c.createProvider.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// UpdateProvider calls platform.provider.v1.ProviderService.UpdateProvider.
func (c *providerServiceClient) UpdateProvider(ctx context.Context, req *v1.UpdateProviderRequest) (*v1.UpdateProviderResponse, error) {
	response, err := c.updateProvider.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// DeleteProvider calls platform.provider.v1.ProviderService.DeleteProvider.
func (c *providerServiceClient) DeleteProvider(ctx context.Context, req *v1.DeleteProviderRequest) (*v1.DeleteProviderResponse, error) {
	response, err := c.deleteProvider.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ProbeProviderObservability calls platform.provider.v1.ProviderService.ProbeProviderObservability.
func (c *providerServiceClient) ProbeProviderObservability(ctx context.Context, req *v1.ProbeProviderObservabilityRequest) (*v1.ProbeProviderObservabilityResponse, error) {
	response, err := c.probeProviderObservability.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// WatchProviderStatusEvents calls platform.provider.v1.ProviderService.WatchProviderStatusEvents.
func (c *providerServiceClient) WatchProviderStatusEvents(ctx context.Context, req *v1.WatchProviderStatusEventsRequest) (*connect.ServerStreamForClient[v1.WatchProviderStatusEventsResponse], error) {
	return c.watchProviderStatusEvents.CallServerStream(ctx, connect.NewRequest(req))
}

// ListVendors calls platform.provider.v1.ProviderService.ListVendors.
func (c *providerServiceClient) ListVendors(ctx context.Context, req *v1.ListVendorsRequest) (*v1.ListVendorsResponse, error) {
	response, err := c.listVendors.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListCLIDefinitions calls platform.provider.v1.ProviderService.ListCLIDefinitions.
func (c *providerServiceClient) ListCLIDefinitions(ctx context.Context, req *v1.ListCLIDefinitionsRequest) (*v1.ListCLIDefinitionsResponse, error) {
	response, err := c.listCLIDefinitions.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ListTemplates calls platform.provider.v1.ProviderService.ListTemplates.
func (c *providerServiceClient) ListTemplates(ctx context.Context, req *v1.ListTemplatesRequest) (*v1.ListTemplatesResponse, error) {
	response, err := c.listTemplates.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ApplyTemplate calls platform.provider.v1.ProviderService.ApplyTemplate.
func (c *providerServiceClient) ApplyTemplate(ctx context.Context, req *v1.ApplyTemplateRequest) (*v1.ApplyTemplateResponse, error) {
	response, err := c.applyTemplate.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ProviderServiceHandler is an implementation of the platform.provider.v1.ProviderService service.
type ProviderServiceHandler interface {
	ListProviderSurfaces(context.Context, *v1.ListProviderSurfacesRequest) (*v1.ListProviderSurfacesResponse, error)
	ListProviders(context.Context, *v1.ListProvidersRequest) (*v1.ListProvidersResponse, error)
	CreateProvider(context.Context, *v1.CreateProviderRequest) (*v1.CreateProviderResponse, error)
	UpdateProvider(context.Context, *v1.UpdateProviderRequest) (*v1.UpdateProviderResponse, error)
	DeleteProvider(context.Context, *v1.DeleteProviderRequest) (*v1.DeleteProviderResponse, error)
	ProbeProviderObservability(context.Context, *v1.ProbeProviderObservabilityRequest) (*v1.ProbeProviderObservabilityResponse, error)
	WatchProviderStatusEvents(context.Context, *v1.WatchProviderStatusEventsRequest, *connect.ServerStream[v1.WatchProviderStatusEventsResponse]) error
	ListVendors(context.Context, *v1.ListVendorsRequest) (*v1.ListVendorsResponse, error)
	ListCLIDefinitions(context.Context, *v1.ListCLIDefinitionsRequest) (*v1.ListCLIDefinitionsResponse, error)
	ListTemplates(context.Context, *v1.ListTemplatesRequest) (*v1.ListTemplatesResponse, error)
	ApplyTemplate(context.Context, *v1.ApplyTemplateRequest) (*v1.ApplyTemplateResponse, error)
}

// NewProviderServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProviderServiceHandler(svc ProviderServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	providerServiceMethods := v1.File_platform_provider_v1_provider_service_proto.Services().ByName("ProviderService").Methods()
	providerServiceListProviderSurfacesHandler := connect.NewUnaryHandlerSimple(
		ProviderServiceListProviderSurfacesProcedure,
		svc.ListProviderSurfaces,
		connect.WithSchema(providerServiceMethods.ByName("ListProviderSurfaces")),
		connect.WithHandlerOptions(opts...),
	)
	providerServiceListProvidersHandler := connect.NewUnaryHandlerSimple(
		ProviderServiceListProvidersProcedure,
		svc.ListProviders,
		connect.WithSchema(providerServiceMethods.ByName("ListProviders")),
		connect.WithHandlerOptions(opts...),
	)
	providerServiceCreateProviderHandler := connect.NewUnaryHandlerSimple(
		ProviderServiceCreateProviderProcedure,
		svc.CreateProvider,
		connect.WithSchema(providerServiceMethods.ByName("CreateProvider")),
		connect.WithHandlerOptions(opts...),
	)
	providerServiceUpdateProviderHandler := connect.NewUnaryHandlerSimple(
		ProviderServiceUpdateProviderProcedure,
		svc.UpdateProvider,
		connect.WithSchema(providerServiceMethods.ByName("UpdateProvider")),
		connect.WithHandlerOptions(opts...),
	)
	providerServiceDeleteProviderHandler := connect.NewUnaryHandlerSimple(
		ProviderServiceDeleteProviderProcedure,
		svc.DeleteProvider,
		connect.WithSchema(providerServiceMethods.ByName("DeleteProvider")),
		connect.WithHandlerOptions(opts...),
	)
	providerServiceProbeProviderObservabilityHandler := connect.NewUnaryHandlerSimple(
		ProviderServiceProbeProviderObservabilityProcedure,
		svc.ProbeProviderObservability,
		connect.WithSchema(providerServiceMethods.ByName("ProbeProviderObservability")),
		connect.WithHandlerOptions(opts...),
	)
	providerServiceWatchProviderStatusEventsHandler := connect.NewServerStreamHandlerSimple(
		ProviderServiceWatchProviderStatusEventsProcedure,
		svc.WatchProviderStatusEvents,
		connect.WithSchema(providerServiceMethods.ByName("WatchProviderStatusEvents")),
		connect.WithHandlerOptions(opts...),
	)
	providerServiceListVendorsHandler := connect.NewUnaryHandlerSimple(
		ProviderServiceListVendorsProcedure,
		svc.ListVendors,
		connect.WithSchema(providerServiceMethods.ByName("ListVendors")),
		connect.WithHandlerOptions(opts...),
	)
	providerServiceListCLIDefinitionsHandler := connect.NewUnaryHandlerSimple(
		ProviderServiceListCLIDefinitionsProcedure,
		svc.ListCLIDefinitions,
		connect.WithSchema(providerServiceMethods.ByName("ListCLIDefinitions")),
		connect.WithHandlerOptions(opts...),
	)
	providerServiceListTemplatesHandler := connect.NewUnaryHandlerSimple(
		ProviderServiceListTemplatesProcedure,
		svc.ListTemplates,
		connect.WithSchema(providerServiceMethods.ByName("ListTemplates")),
		connect.WithHandlerOptions(opts...),
	)
	providerServiceApplyTemplateHandler := connect.NewUnaryHandlerSimple(
		ProviderServiceApplyTemplateProcedure,
		svc.ApplyTemplate,
		connect.WithSchema(providerServiceMethods.ByName("ApplyTemplate")),
		connect.WithHandlerOptions(opts...),
	)
	return "/platform.provider.v1.ProviderService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProviderServiceListProviderSurfacesProcedure:
			providerServiceListProviderSurfacesHandler.ServeHTTP(w, r)
		case ProviderServiceListProvidersProcedure:
			providerServiceListProvidersHandler.ServeHTTP(w, r)
		case ProviderServiceCreateProviderProcedure:
			providerServiceCreateProviderHandler.ServeHTTP(w, r)
		case ProviderServiceUpdateProviderProcedure:
			providerServiceUpdateProviderHandler.ServeHTTP(w, r)
		case ProviderServiceDeleteProviderProcedure:
			providerServiceDeleteProviderHandler.ServeHTTP(w, r)
		case ProviderServiceProbeProviderObservabilityProcedure:
			providerServiceProbeProviderObservabilityHandler.ServeHTTP(w, r)
		case ProviderServiceWatchProviderStatusEventsProcedure:
			providerServiceWatchProviderStatusEventsHandler.ServeHTTP(w, r)
		case ProviderServiceListVendorsProcedure:
			providerServiceListVendorsHandler.ServeHTTP(w, r)
		case ProviderServiceListCLIDefinitionsProcedure:
			providerServiceListCLIDefinitionsHandler.ServeHTTP(w, r)
		case ProviderServiceListTemplatesProcedure:
			providerServiceListTemplatesHandler.ServeHTTP(w, r)
		case ProviderServiceApplyTemplateProcedure:
			providerServiceApplyTemplateHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProviderServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProviderServiceHandler struct{}

func (UnimplementedProviderServiceHandler) ListProviderSurfaces(context.Context, *v1.ListProviderSurfacesRequest) (*v1.ListProviderSurfacesResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.provider.v1.ProviderService.ListProviderSurfaces is not implemented"))
}

func (UnimplementedProviderServiceHandler) ListProviders(context.Context, *v1.ListProvidersRequest) (*v1.ListProvidersResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.provider.v1.ProviderService.ListProviders is not implemented"))
}

func (UnimplementedProviderServiceHandler) CreateProvider(context.Context, *v1.CreateProviderRequest) (*v1.CreateProviderResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.provider.v1.ProviderService.CreateProvider is not implemented"))
}

func (UnimplementedProviderServiceHandler) UpdateProvider(context.Context, *v1.UpdateProviderRequest) (*v1.UpdateProviderResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.provider.v1.ProviderService.UpdateProvider is not implemented"))
}

func (UnimplementedProviderServiceHandler) DeleteProvider(context.Context, *v1.DeleteProviderRequest) (*v1.DeleteProviderResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.provider.v1.ProviderService.DeleteProvider is not implemented"))
}

func (UnimplementedProviderServiceHandler) ProbeProviderObservability(context.Context, *v1.ProbeProviderObservabilityRequest) (*v1.ProbeProviderObservabilityResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.provider.v1.ProviderService.ProbeProviderObservability is not implemented"))
}

func (UnimplementedProviderServiceHandler) WatchProviderStatusEvents(context.Context, *v1.WatchProviderStatusEventsRequest, *connect.ServerStream[v1.WatchProviderStatusEventsResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("platform.provider.v1.ProviderService.WatchProviderStatusEvents is not implemented"))
}

func (UnimplementedProviderServiceHandler) ListVendors(context.Context, *v1.ListVendorsRequest) (*v1.ListVendorsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.provider.v1.ProviderService.ListVendors is not implemented"))
}

func (UnimplementedProviderServiceHandler) ListCLIDefinitions(context.Context, *v1.ListCLIDefinitionsRequest) (*v1.ListCLIDefinitionsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.provider.v1.ProviderService.ListCLIDefinitions is not implemented"))
}

func (UnimplementedProviderServiceHandler) ListTemplates(context.Context, *v1.ListTemplatesRequest) (*v1.ListTemplatesResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.provider.v1.ProviderService.ListTemplates is not implemented"))
}

func (UnimplementedProviderServiceHandler) ApplyTemplate(context.Context, *v1.ApplyTemplateRequest) (*v1.ApplyTemplateResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.provider.v1.ProviderService.ApplyTemplate is not implemented"))
}
